SAP/cloud-sdk-ios-fiori

- CONTRIBUTING.md
- scripts/addSwiftLintRunScriptToXcodeProj.py
- scripts/pre-commit.sh
- scripts/runSwiftLintCheck.sh
- setupForCollaborators.sh
script will install a pre-commit gith hook to run a SwiftLint check automatically before commmitting your sources. It will also add a run script to ensure that SwiftLint checks are getting executed when you are working within the Xcode project file.
> chore: introduce shell script to setup collaborators

- CHANGELOG.md
- Package.resolved
- Package.swift
Tested with my fork version that issue is fixed. After merging this PR I will create Github release
> chore(release): 0.5.1

- .czrc
- .github/configActions/commitlint.config.js
- .github/workflows/pr_only.yml
- CONTRIBUTING.md
- README.md
- scripts/githooks/pre-push
- scripts/githooks/prepare-commit-msg
- scripts/installGitHooks.sh
- setupForCollaborators.sh
also provide local tooling when running `setupForCollaborators.sh`
> ci: support conventional commits

- .github/workflows/jazzy.yml
- CONTRIBUTING.md
- README.md
- scripts/generateRelease.sh
- add version info for script dependencies in CONTRIBUTING.md
- improve README
- provide sample for future script to automate release process
- remove if push condition in jazzy.yml
> chore: housekeeping

- Sources/FioriCharts/Extensions/NumberFormatter+Extensions.swift
- Sources/FioriCharts/FioriChartsLibraryContent.swift
- Sources/FioriCharts/TestCases/Tests.swift
Relevant for Xcode 12 and beyond
> feat: add custom views of FioriCharts to Xcode library

- Sources/FioriIntegrationCards/Components/Analytical/Model/AnalyticalCard.swift
- Sources/FioriIntegrationCards/Components/Common/Model/BaseCard.swift
BREAKING CHANGE: Class name changed
resolves #59
> refactor: rename BaseBaseCard to BackingCard

- Apps/Examples/Examples/FioriCharts/ChartsContentView.swift
https://developer.apple.com/forums/thread/653247
fix #93
> test: fix Xcode 12 beta bug when selecting Chart in ExamplesApp

- Sources/FioriIntegrationCards/Components/Timeline/UI/TimelineItemView.swift
the issue was caught becasue of the code order of line 31 and 32
✅ Closes: #106
> fix: 🐛 fix the flickering issue on main branch

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/rebase.yml
- .swiftlint.yml
- explicitly ignore folders in SwiftLint so that HoundCI does not report violations in those folders
- add the capability to trigger rebase for pull request via comment `/rebase`
- improve bug report template
> DevOps improvements

- Sources/FioriIntegrationCards/Components/Table/UI/TableTitleRowView.swift
> fix: 🐛 fix the problem that title row does not align with card

- .github/workflows/ci-beta.yml
- Apps/Examples/Examples/FioriSwiftUICore/SegmentedControl/SegmentedControl+Chart.swift
- CONTRIBUTING.md
- Sources/FioriCharts/Charts/Common/NoDataView.swift
- Sources/FioriSwiftUICore/NoDataView.swift
- setupForCollaborators.sh
Solves the problem that the internal `NoDataView` shows the text "No Data" in English only
Prerequisites (fulfilled)
- [build: set minimum swift-tools-version to 5.3](https://github.com/SAP/cloud-sdk-ios-fiori/commit/10045daf4f1d743730e0dfae9a5aaad0aaefcbe6) on `main-beta` branch
- [ci: setup translation pipeline](https://github.com/SAP/cloud-sdk-ios-fiori/commit/0dce8a5146fb75a985fc1b14c64496348d6bb0de) to get translations for string entries in *.lproj
Please note that using Xcode project for package developers is no longer possible. Building from a Xcode project (generated by `swift package generate-xcodeproj`) would fail with Error `Type 'Bundle' has no member 'module'` . See https://developer.apple.com/forums/thread/650278 for further details
> Localization of text in NoDataView (depends on Swift 5.3)

- Sources/FioriCharts/Resources/hu.lproj/Localizable.strings
- Sources/FioriSwiftUICore/hu.lproj/FioriSwiftUICore.strings
> Translation Delivery

- .github/workflows/jazzy.yml
- scripts/generateDocumentation.sh
also don't require xcodeproj file
> ci: allow to manually trigger documentation deployment

- .github/workflows/recordSnapshotImages.yml
also don't require xcode project existence anymore
> ci: allow to manually trigger snapshot testing

- README.md
- jazzy/Overview_README.md
- remove  "FioriCharts must support point and range selection, equivalent to the current implementation in SAPFiori"
- remove "This project is in development, and should not yet be used productively."
> chore: update README

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriIntegrationCards/SampleData/InlineTestCases.swift
- Apps/Examples/Examples/FioriIntegrationCards/SampleData/listicon.json
- Apps/Examples/ExamplesTests/SnapshotTests/FioriIntegrationCards/ListCardSnapshotTests.swift
- Sources/FioriIntegrationCards/Components/List/UI/ListItemView.swift
https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/explore/list/icon
> feat: integration cards: support list with icons

- Apps/Examples/Examples/ContentView.swift
- Apps/Examples/Examples/FioriIntegrationCards/IntegrationCardsContentView.swift
- Apps/Examples/Examples/FioriIntegrationCards/SampleData/BundleTestCases.swift
- Apps/Examples/Examples/FioriIntegrationCards/SampleData/DataRequestTestCases.swift
- Apps/Examples/Examples/FioriIntegrationCards/SampleData/InlineTestCases.swift
- Sources/FioriIntegrationCards/Components/Timeline/UI/TimelineItemView.swift
> Integration Card: support owner/ownerImage in Timeline as well as organize tests

- Sources/FioriSwiftUICore/_generated/ViewModels/API/ContactItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ActivityItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ActivityItems+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ChartFloorplan+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/CollectionItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ContactItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/HeaderChart+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/KPIItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/KeyValueItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ListPickerItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ObjectHeader+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ObjectItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ProfileHeader+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/SectionHeader+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/TimelineGridItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/TimelineItem+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Init+Extensions/ContactItem+Init.generated.swift
- sourcery/stencils/main_phase/model_decl_base.swifttemplate
- sourcery/stencils/main_phase/noviewbuilderbased_model_decl.swifttemplate
- sourcery/stencils/post_phase/composite_model_decl.swifttemplate
add LibraryContentProvider snippet for +View.generated.swift files so that contributors don't forget to implement view-specific
LibraryContentProvider
> Sourcery Code Generation: add LibraryContentProvider code stub

- Sources/FioriSwiftUICore/_generated/ViewModels/API/ActivityItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ChartFloorplan+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/CollectionItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ContactItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/HeaderChart+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/KPIItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/KeyValueItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ListPickerItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectHeader+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ProfileHeader+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/SectionHeader+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/TimelineGridItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/TimelineItem+API.generated.swift
- sourcery/.lib/Sources/utils/Array+Variable.swift
- sourcery/stencils/main_phase/model_decl_base.swifttemplate
- sourcery/stencils/post_phase/composite_model_decl.swifttemplate
being able to identify if `EmptyView` is used for a view (e.g. Subtitle)
> chore: 🤖 new private/internal model variables for emptView det

- Apps/Examples/Examples/FioriSwiftUICore/Experimental/Examples/ContactItemActionItemsExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Experimental/Examples/ContactItemStateAndDataBindingExample.swift
- README.md
- Sources/FioriSwiftUICore/Components/MultiPropertyComponents.swift
- Sources/FioriSwiftUICore/LibraryPreview/LibraryPreviewData+Person.swift
- Sources/FioriSwiftUICore/Views/ActivityItems+View.swift
- Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ActivityItems+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ContactItem+API.generated.swift
- sourcery/.lib/Sources/utils/Type+Extensions.swift
https://github.com/SAP/cloud-sdk-ios-fiori/pull/214#discussion_r598923288
> chore: 🤖 do not append `Closure` to generated closure props

- Sources/FioriCharts/Charts/Common/GridLinesAndChartView.swift
- Sources/FioriCharts/Extensions/View+Extensions.swift
allow external gestures work simultaneously with internal gestuers in a
chart
> feat: 🎸 allow multiple gestures work simultaneously in a chart

- Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
Allow proper calculation of intrinsic content size by removing geometry reader
> fix: 🐛 Remove geometry reader

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
- Sources/FioriSwiftUICore/SignatureView/DrawingPad.swift
- Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
- Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/SignatureCaptureViewTests.swift
> fix: signature capture view height and localization

- .github/workflows/dependencyManagement.yml
as repository/package swift tools version is 5.3 nowadays
> ci: use swift-package-dependencies-check@1.1.0

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
- Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/SignatureCaptureViewTests.swift
fix padding and behavior flow according to the spec
> fix: 🐛 padding and behavior per spec

- Sources/FioriCharts/Resources/de-CH.lproj/Localizable.strings
- Sources/FioriCharts/Resources/it-CH.lproj/Localizable.strings
- Sources/FioriSwiftUICore/_localization/de-CH.lproj/FioriSwiftUICore.strings
- Sources/FioriSwiftUICore/_localization/it-CH.lproj/FioriSwiftUICore.strings
> feat: Translation Delivery

- Sources/FioriSwiftUICore/Views/SideBar+View.swift
- Sources/FioriSwiftUICore/Views/SideBarListItem+View.swift
Improve side bar layout and styling per Global Design review comments.
> refactor: 💡 improve side bar styling

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Sources/FioriCharts/Extensions/View+Extensions.swift
Make ifApply() to be available for other modules
> feat: 🎸 make FioriCharts's ifApply() public

- .github/workflows/pr_only.yml
1. Disable Snapshot Tests
2. Add comment to check for comments in `.strings` file whenever a text was added
Improve point 2 by automatic check when issue 15 of https://github.com/dral3x/StringsLint is available
> add LocalizableTextCommentsCheck

- .github/workflows/pr_only.yml
- .stringslint.yml
- Sources/FioriCharts/Resources/en.lproj/Localizable.strings
- Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings
to detect if developer added comment to localizable text in strings.file
> ci: 🎡 LocalizableTextCommentsCheck uses StringsLint

- Apps/Examples/Examples/FioriIntegrationCards/SampleData/DataRequestTestCases.swift
- Sources/FioriIntegrationCards/Components/List/UI/ListCardView.swift
- restore examples for data requests (incl. manifest parameters)
- honor maxItems in `List` integration card
> Integration Cards fixes

- Sources/FioriThemeManager/Palettes/PaletteV5.swift
This adds the dependency on a fix to customer ticket for FUISegmentedControl.
> refactor: 💡 add contrast colors for background

- Sources/FioriSwiftUICore/DataTable/DataTableItem.swift
- Sources/FioriSwiftUICore/DataTable/DataTextItem.swift
- Sources/FioriSwiftUICore/DataTable/ItemView.swift
- Sources/FioriSwiftUICore/DataTable/LayoutData.swift
Co-authored-by: Bill Zhou <bill.zhou01@sap.com>
> feat: 🎸 add uifont to DataTextItem in DataTable (#362)

- Sources/FioriSwiftUICore/SignatureView/ScribbleView.swift
- Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
✅ Closes: part of BCP 2170239589
> fix: 🐛 stroke not smooth problem when stroke width is large

- Sources/FioriThemeManager/72-Fonts/Font+Register.swift
replace print statements with os_log in Font+Register.swift
> fix: 🐛 replace print statements with os_log

- Sources/FioriSwiftUICore/DataTable/TableViewLayout.swift
For HCPSDKFIORIUIKIT-2117 Data Table Styling Update
> fix: 🐛 improve data table styling

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
- Sources/FioriSwiftUICore/SignatureView/ScribbleView.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/KPIProgressItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectHeader+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/SignatureCaptureView+API.generated.swift
Adding timestamp and watermark to SignatureCaptureView
✅ Closes: BCP 2170239589
> feat: 🎸 [BCP:2170239589]Signature add timestamp and watermark

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
Signature timestamp formatter not applied problem
✅ Closes: 2270089550
> fix: 🐛 [BCP:2270089550] Fix signature timestamp formatter

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
Signature timestamp formatter not applied problem
✅ Closes: 2270089550
Cherry-picked from integrationSAPFiori7.0
> fix: 🐛 [BCP:2270089550] Fix signature timestamp formatterm

- CHANGELOG.md
- jazzy/FioriIntegrationCards_README.md
- jazzy/Overview_README.md
- scripts/generateDocumentation.sh
- chore: 🤖 remove FioriIntegrationCards from API documentation
- chore: 🤖 2.2.0
Once merged I'll create a GitHub release (& tag)
> Preparing minor release 2.2.0

- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV7.swift
Designers update chart colors: chart7 and chart11
> feat: [JIRA:HCPSDKFIORIUIKIT-2180]update chart colors: chart7 and chart11

- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
✅ Closes: BCP:2170177121
Also, fix 44 minimum width and height for buttons
> fix: 🐛 [BCP:2170177121] InlineSignature flickering problem

- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
✅ Closes: BCP:2170177121
Cherry-picked from main.
(cherry picked from commit ff32b9f647a2c85e54bf3241c55d4a2aa3867fea)
> fix: 🐛 [BCP:2170177121] InlineSignature flickering problem (#449)

- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV7.swift
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
adding 6 new colors to FUIColorStyle. 
These colors will be used to enable custom branding for specific UI Elements via nss file
> feat:[JIRA:HCPSDKFIORIUIKIT-2210] Add custom colors to FUIColorStyle

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
no truncation for long key name
✅ Closes: [JIRA:HCPSDKFIORIUIKIT-2158]
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2158] InlineSignatureFormCell

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriThemeManager/Colors.swift
- Apps/Examples/Examples/FioriThemeManager/FioriThemeManagerContentView.swift
https://user-images.githubusercontent.com/4176826/191872057-33018a9a-fd64-475d-96d2-a5a7771fddee.mp4
> docs: ✏️ view latest colors / custom color palette in ExampleApp

- CHANGELOG.md
CHANGELOG for 3.0.0
Once merged I'll create a GitHub release (& tag)
> chore: 🤖 3.0.0

- Sources/FioriCharts/Charts/Common/ChartUtility.swift
- Sources/FioriCharts/Charts/Common/GridLinesAndChartView.swift
- Sources/FioriThemeManager/Colors/ColorStyle.swift
- fix: 🐛 [BCP: 675290] improve selection as same as rombichart (#464)
- chore: 🤖 exclude ColorStyle extension for SAPFiori target
> fix: 🐛 [BCP: 675290] improve selection as same as rombichart (#464)

- Sources/FioriThemeManager/Colors/Color+Extension.swift
- Sources/FioriThemeManager/StyleSheet/Internal/StyleSheetConverter.swift
- Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetSettingsIntegrationTests.swift
- Tests/FioriSwiftUITests/FioriThemeManager/TestResources/styleSheet.nss
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
> fix: 🐛 3-digit hex color is not parsed correctly

- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
- Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPicker.swift
- Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
A searchable list picker that support tracking alive or not.
> feat: 🎸 HCPSDKFIORIUIKIT-2219 a searchable list picker

- Apps/Examples/Examples/FioriThemeManager/Colors.swift
- Apps/Examples/Examples/FioriThemeManager/FioriThemeManagerContentView.swift
- Sources/FioriThemeManager/Colors/Color+Extension.swift
- Sources/FioriThemeManager/ThemeManager.swift
- Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetSettingsIntegrationTests.swift
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
> fix: 🐛 Custom colors were not updated when appearance changed

- CHANGELOG.md
(cherry picked from commit ca13c69664b0c371df8d2cde6832c0d91648dcf2)
Copying over CHANGELOG entries for 3.0.2 (created from rel-3.0 branch) into main
> chore: 🤖 3.0.2

- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV7.swift
* fix:[BCP:2270157767] deprecated chart 10 and chart 11
* fix:[BCP:2270157767] add note for chart 10 and chart 11
* fix:[BCP:2270157767] Code Formatting Check
Co-authored-by: c5342342 <kun.zuo@sap.com>
Co-authored-by: Bill Zhou <bill.zhou01@sap.com>
> fix:🐛 [BCP:2280197469] cherry-pick (#490)

- Sources/FioriSwiftUICore/Views/SearchableListContent.swift
> fix: 🐛 keep the search bar beneath navigation bar title

- Sources/FioriSwiftUICore/Views/EmptyStateView+View.swift
fix: [SN:CS20230004967806] FUIEmptyStateView not centered and content clickable. Cherry pick from main.
> fix: 🐛 [SN:CS20230004967806] FUIEmptyStateView not centered

- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV7.swift
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
Add a new color style, navBarTitleLabel, to be used specifically for nav bar title. Its hex value is the same as primaryLabel.
> feat: 🎸 HCPSDKFIORIUIKIT-2287 Add color navBarTitleLabel

- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV7.swift
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
> feat: 🎸 HCPSDKFIORIUIKIT-2287 Add color navBarTitleLab

- Sources/FioriSwiftUICore/DataTable/DataTable.swift
- Sources/FioriSwiftUICore/DataTable/GridTableView.swift
- Sources/FioriSwiftUICore/DataTable/InlineEditingView.swift
- Sources/FioriSwiftUICore/DataTable/ItemView.swift
- Sources/FioriSwiftUICore/DataTable/TableLayoutManager.swift
- Sources/FioriSwiftUICore/DataTable/TableLayoutMangerExtension.swift
- Sources/FioriSwiftUICore/DataTable/TableModel.swift
Add new APIs to allow adjustment of TextField cell position in DataTable when keyboard shows up
> fix: 🐛 [bcp: 2370038492] adjust TextField pos in DataTabel

- Apps/Examples/Examples/FioriThemeManager/IconLibraryExample.swift
- Sources/FioriSwiftUICore/DataTable/LayoutData.swift
- Sources/FioriSwiftUICore/DataTable/TableLayoutManager.swift
- Sources/FioriSwiftUICore/DataTable/TableLayoutMangerExtension.swift
- Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetParserTests.swift
Job running "mint run swiftformat --verbose ." reported format error. Fixed the offending files
BREAKING CHANGE: 🧨 No
> chore: 🤖 CI job reported format swift code error

- Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
- Sources/FioriSwiftUICore/Views/Action+View.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
- Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings
✅ Closes: 2370082757
Cherry-picked from main
(cherry picked from commit 6d09d0ffc88c47d575770721faa3e4f57f5aca93)
> fix: 🐛 [BCP:2370082757] Fix SignatureCaptureView VO issues (#602)

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
- Apps/Examples/Examples/FioriSwiftUICore/FormCells/TextInputInfoViewExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Indicator/LinearProgressIndicatorExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/LinearProgressIndicatorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/LinearProgressIndicatorViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextInputInfoViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Icon/Icon.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/InformationView/InformationView.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LinearProgressIndicator/LinearProgressIndicator.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LinearProgressIndicator/LinearProgressIndicatorStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LinearProgressIndicatorView/LinearProgressIndicatorView.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LinearProgressIndicatorView/LinearProgressIndicatorViewStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/TextInputInfoView/TextInputInfoView.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/TextInputInfoView/TextInputInfoViewStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/StyleConfiguration+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
feat: [JIRA:HCPSDKFIORIUIKIT-2458]Linear Progress Indicator and TextInputInfoView
✅ Closes: HCPSDKFIORIUIKIT-2458
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2458]Linear Progress Indicator and TextInputInfoView

- Sources/FioriSwiftUICore/Views/ContactItem+View.swift
The ContactCell referred to as ContactItem in SwiftUI as well.
The "preferredFioriColor" in the description has been changed to ".tertiaryLabel" (line#27)
✅ Closes: HCPSDKFIORIUIKIT-2504
> feat: 🎸 [HCPSDKFIORIUIKIT-2503] [New Color System] Contact Item

- Apps/Examples/Examples/FioriThemeManager/Colors.swift
- Apps/Examples/Examples/FioriThemeManager/FioriThemeManagerContentView.swift
- Sources/FioriThemeManager/Colors/ColorStyle.swift
- Sources/FioriThemeManager/Palettes/PaletteV8.swift
- Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
1. As per Design, added 6 new color styles for Joule Mobile Client
2. Updated unit test for V8
3. Added UI tests for Gradient Color effect ( borderline, background )
> feat: 🎸 [HCPSDKFIORIUIKIT-2601]Add additional color style to V8

- Sources/FioriSwiftUICore/FioriButton/FioriButtonStyleProvider.swift
- Sources/FioriSwiftUICore/Views/ActivationScreen+View.swift
- Sources/FioriSwiftUICore/Views/EULAView+View.swift
- Sources/FioriSwiftUICore/Views/InfoView+View.swift
- Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
- Sources/FioriSwiftUICore/Views/SliderPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SwitchPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentPage+View.swift
- Sources/FioriSwiftUICore/Views/WelcomeScreen+View.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardMainHeaderStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardMediaStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift
- updates to integrate semibold font weight
> feat: [JIRA: HCPSDKFIORIUIKIT-2542] Semibold System Update

- Sources/FioriThemeManager/Palettes/PaletteV8.swift
Design Team wants to update jouleBrand hex value
> fix: 🐛 HCPSDKFIORIUIKIT-2641 Joule Color Hex Value update

- Apps/Examples/Examples/FioriSwiftUICore/FormViews/TextFieldFormViewExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextFieldFormViewStyle.fiori.swift
Cherry-picked from main.
(cherry picked from commit c5b45867a7f7fa46c51736891b6698082f960d55)
> fix: 🐛 [JIRA:0] KeyValue and TextFIeld formcell title color fix (#697)

- Apps/Examples/Examples/FioriSwiftUICore/SearchBar/SearchFontAndColor.swift
Also to configure navigation bar title theming
> test: 💍 update search testcase for background color

- Sources/FioriCharts/Charts/Common/XAxisView.swift
- Sources/FioriCharts/Charts/Common/YAxisView.swift
- Sources/FioriCharts/Model/ChartLabelAttributes.swift
add two variables(font and backgroundColor) to ChartLabelAttributes, for user to custom chart label attributes conveniently
✅ Closes: #692
> feat: 🎸 [JIRA:IOSSDKBUG-5] add variables to ChartLabelAttributes

- Sources/FioriCharts/Charts/Common/XAxisView.swift
- Sources/FioriCharts/Charts/Common/YAxisView.swift
- Sources/FioriCharts/Model/ChartLabelAttributes.swift
add two variables(font and backgroundColor) to ChartLabelAttributes, for user to custom chart label attributes conveniently
✅ Closes: #692
> feat: 🎸 [JIRA:IOSSDKBUG-5] add variables to ChartLabelAttribute

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
- Apps/Examples/Examples/FioriSwiftUICore/Views/KeyValueItemExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Views/OtherViewExamples.swift
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
- Sources/FioriSwiftUICore/Views/KeyValueItem+View.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/KeyValueItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Init+Extensions/KeyValueItem+Init.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Model+Extensions/KeyValueItemModel+Extensions.generated.swift
> feat: 🎸 [JIRA:IOSSDKBUG-256]KeyValueItem: vertical aligned

- Apps/Examples/Examples/FioriSwiftUICore/SideBar/EditableSideBarExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/SideBarStyle.fiori.swift
This PR handle the changes on SideBar according to the [second round UX review](https://www.figma.com/design/HIzRE8f9fCeVp91OlixmNJ/Sidebar-(iOS)?node-id=5601-32384&t=71wYjhHKw0xr8Agy-0#874356359)
> fix: 🐛 addressing UX review comments for SideBar

- Apps/Examples/Examples/FioriSwiftUICore/FormCells/StepperViewExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextInputFieldStyle.fiori.swift
- Add number style for TextInputField
- Check the text input value for the stepper value range
- Add style for disable the increaseButton and decreaseButton when editing ✅ Closes: JIRA:IOSSDKBUG-155 FUIStepperView disable decreaseButton and increaseButton not works
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2635]SwiftUI Stepper enhancement

- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
To organize the test cases better, group tests into different sections.
> test: 💍 group test cases into different sections"

- Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMessageCustomInitExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMessageModifierExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/BannerMessage/BannerMessage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/BannerMessage/BannerMessageStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
1. Add icon support for banner message.
2. Add new cases for long title and different styles.
> fix: 🐛 [JIRA: HCPSDKFIORIUIKIT-2478] banner message style

- Apps/Examples/Examples/FioriSwiftUICore/FormCells/StepperViewExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DecrementAction/DecrementAction.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/IncrementAction/IncrementAction.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperField/StepperField.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperView/StepperView.generated.swift
- sourcery/.lib/Sources/utils/ForStyleableComponent/Type+Extension.swift
Fixed below issues:
Addressed Stepper UI review issues;
Added importStatement type in Sourcery template;
Disabled decrement/increment action when textfield is focused.
> fix: 🐛 [JIRA: FIORIDESIGN-12263] fix UI review issues

- Sources/FioriSwiftUICore/DataTable/DataTable.swift
- Sources/FioriSwiftUICore/DataTable/LayoutData.swift
fix item padding in regular or compact mode, also in edit mode
> fix: 🐛 [JIRA:IOSSDKBUG-264] No left padding for the 1st column in DataTable

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Sources/FioriSwiftUICore/Views/Carousel.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardHeaderStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift
Added same height Carousel for card
isSameHeight is false and alignment is top:
> feat: 🎸 [JIRA: 0] add isSameHeight in Carousel and update some cards based on reviews

- Apps/Examples/Examples/FioriSwiftUICore/StepProgressIndicator/StepProgressIndicatorExample.swift
- Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
- Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
* Add image support for the Step Progress Indicator Component
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2716]Step Progress Indicator Enhancement

- Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
- Sources/FioriSwiftUICore/FioriButton/FioriButtonStyleProvider.swift
According to the spec,  the FioriButton should have the minimum visible height 38pt and touch area height 44pt.
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2729] Update button visible and touch area height

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/DateTimePickerExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/DateTimePickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/ValueLabelStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePickerStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ValueLabel/ValueLabel.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ValueLabel/ValueLabelStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
1st PR for DateTimePicker
Features to be implemented later:
- vertical stacked layout for long labels and dynamic type
- option to set no date selected string, date formatter
- accessibility support
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2687] SwiftUI DateTimePicker(1)

- Apps/Examples/Examples/FioriSwiftUICore/FormViews/KeyValueFormViewExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
> fix: 🐛 [JIRA:IOSSDKBUG-324]Usage of SwiftUI KeyValueFormView

- .github/workflows/ci.yml
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
This is combined with `ObjectItem`. This is an accident.
> fix: 🐛 [JIRA: 0] remove unnecessary environments tag

- Apps/Examples/Examples/FioriSwiftUICore/FormViews/NoteFormViewExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/FormViews/TitleFormViewExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/PlaceholderTextEditorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/PlaceholderTextFieldStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextFieldFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextInputInfoViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TitleFormViewStyle.fiori.swift
> fix: 🐛 [JIRA:FIORIDESIGN-12289] fix textinput review comments

- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
- Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
- Sources/FioriSwiftUICore/Views/FilterFeedbackBarButton+View.swift
- Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/OptionListPickerItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Model+Extensions/OptionListPickerItemModel+Extensions.generated.swift
cherrypick from https://github.com/SAP/cloud-sdk-ios-fiori/pull/807
> feat: 🎸 [JIRA:IOSSDKBUG-347] FilterFeedbackBar picker enhance

- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
- Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
Not show selected value on the bar title for single selected
> feat: 🎸 HCPSDKFIORIUIKIT-2783 SwiftUI FilterFeedbackBar

- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Fixed the layout issue in the configuration popover.
> fix: 🐛 [JIRA:IOSSDKBUG-347]FilterFeedbackBar picker enhancement

- Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
✅ Closes: HCPSDKFIORIUIKIT-2707
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2707] spec update for icon size

- Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageCustomInitExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/BannerMessage/BannerMessage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/IllustratedMessage/IllustratedMessage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SideBar/SideBar.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/KPIProgressItem+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectHeader+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/SignatureCaptureView+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/SingleStep+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/StepProgressIndicator+API.generated.swift
Title and icon support developer customization in banner message
> feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2717] Feedback Patterns

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
* fix: 🐛 [JIRA:IOSSDKBUG-418] Fix FilterFeedbackBar layout
* fix: 🐛 [JIRA:IOSSDKBUG-418] Fix FilterFeedbackBar layout
---------
> fix: 🐛 [JIRA:IOSSDKBUG-418] Fix FilterFeedbackBar layout (#837)

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+Style.swift
> fix: 🐛 IOSSDKBUG-425 Fiori FilterFeedbackBar items rendering. Cherry pick from main.

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+Style.swift
> fix: 🐛 IOSSDKBUG-425 Fiori FilterFeedbackBar items rendering

- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Fix FilterFeedbackBar layout when searching.
> fix: 🐛 [IOSSDKBUG-416]Fix FilterFeedbackBar layout

- Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectItemAvatarsExample.swift
- Sources/FioriSwiftUICore/Utils/ConfigurationViewWrapper.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TagStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Tag/Tag.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Tag/TagStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
|light|dark|
|-|-|
|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 17 17 26](https://github.com/user-attachments/assets/4f97e770-dfde-4814-8b73-c936004d9383)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 17 17 33](https://github.com/user-attachments/assets/ede98ae4-8548-409b-8d20-66809fadd3b6)|
> refactor: 💡 [JIRA: IOSSDKBUG-402] use styleable tag templete

- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterView+Extensions.swift
- Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterMenuItemContainer.swift
FilterFeedbackBar add stepper view support.
Design: https://www.figma.com/design/5pa7nn87fojjzKQ11KOnSk/Filter-Feedback-Bar-(iOS)?node-id=3019-456396&t=Zf2C99Ij74UEIj2n-4
> feat: 🎸 [HCPSDKFIORIUIKIT-2766] sort & filter enhancement stepper

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
- Sources/FioriSwiftUICore/Views/FilterFeedbackBarButton+View.swift
- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+Style.swift
Adapt FilterFeedbackBar popover background color in visionOS
> fix: 🐛 [JIRA:IOSSDKBUG-413] FilterFeedbackBar in visionOS

- Apps/Examples/Examples/FioriSwiftUICore/FormCells/InformationViewExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/InformationViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/ListPickerItemStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/KeyValueFormView/KeyValueFormView.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ListPickerItem/ListPickerItem.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ListPickerItem/ListPickerItemStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/MandatoryFieldIndicator/MandatoryFieldIndicator.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/TextFieldFormView/TextFieldFormView.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/StyleConfiguration+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
Add Mandatory Fields for Listpicker
Add disable and readonly state for Listpicker
Modify InformationView style to support disable state
> feat: 🎸 JIRA HCPSDKFIORIUIKIT-2765 Mandatory Fields for Listpicker

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterMenuItemContainer.swift
Add accessibilityIdentifier to FilterFeedbackBar and list value.
> fix: 🐛 [IOSSDKBUG-448]FilterFeedbackBar accessibility id

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/SortFilterView+View.swift
- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
> fix: 🐛 [IOSSDKBUG-454] FilterFeedbackBar dark mode design

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
> fix: 🐛 [IOSSDKBUG-454]FilterFeedbackBar dark mode design font

- Sources/FioriSwiftUICore/_FioriStyles/SwitchViewStyle.fiori.swift
- offset switch frame to fix border alignment
> fix: 🐛 [JIRA:IOSSDKBUG-451] Switch border alignment

- Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Add space between selected and (count)
> fix: 🐛 [JIRA:0]FilterFeedbackBar list selected (count)

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+Style.swift
- Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterMenuItemContainer.swift
Stoke border unselected color update to .separatorOpaque.
Fix keyboard control issue.
https://github.com/user-attachments/assets/7e7837f4-4c46-4b48-8f1b-f0dbccddbff0
> fix: 🐛 [IOSSDKBUG-453]FilterFeedbackBar border unselect color

- Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
- Sources/FioriSwiftUICore/_generated/Components/EnvironmentKey+Styles.generated.swift
- Sources/FioriSwiftUICore/_generated/Components/EnvironmentValue+Styles.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/_ProgressIndicator+View.generated.swift
- sourcery/.lib/Sources/utils/Type+Extensions.swift
- add "_ProgressIndicatorModel" to deprecatedComponents in Type+Extensions.swift
> chore: 🤖 Finish Deprecating ProgressIndicator

- Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
- Sources/FioriSwiftUICore/_generated/Components/EnvironmentKey+Styles.generated.swift
- Sources/FioriSwiftUICore/_generated/Components/EnvironmentValue+Styles.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/_ProgressIndicator+View.generated.swift
- sourcery/.lib/Sources/utils/Type+Extensions.swift
> chore: 🤖 finish deprecating ProgressIndicatorModel

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Fix popover height on visionOS.
> fix: 🐛 [IOSSDKBUG-485]Filter layout large fonts on visionOS

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Sources/FioriSwiftUICore/Views/Carousel.swift
> fix: 🐛 avoid conflict btw drag and tap gesture in Carousel

- Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> fix: 🐛 IOSSDKBUG-513 Document Scanner top and bottom white band

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Sources/FioriSwiftUICore/Views/Carousel.swift
Improvements required from JMC:
https://github.com/user-attachments/assets/16f6280a-3122-41e6-b33b-ce3c92bdfc97
> fix: 🐛 improve Carousel by adding contentInsets

- Apps/Examples/Examples/FioriSwiftUICore/CheckoutIndicator/CheckoutIndicatorExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/CheckoutIndicator/CheckoutIndicatorModalExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Indicator/LinearProgressIndicatorExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/CheckoutIndicatorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/LinearProgressIndicatorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/LinearProgressIndicatorViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/LoadingIndicatorViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LoadingIndicator/LoadingIndicator.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/LoadingIndicator/LoadingIndicatorStyle.generated.swift
AI style for LinearProgressIndicator and CheckoutIndicator.
> feat: 🎸 [HCPSDKFIORIUIKIT-2894] AI Progress Indicators

- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
- Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
- Sources/FioriSwiftUICore/Views/_FilterFeedbackBarButton+View.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/FilterFeedbackBarButtonStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ContactItem/ContactItem.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ContactItem/ContactItemStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/FilterFeedbackBarButton/FilterFeedbackBarButton.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/FilterFeedbackBarButton/FilterFeedbackBarButtonStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/HeaderChart/HeaderChart.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/HeaderChart/HeaderChartStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SectionFooter/SectionFooter.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SectionFooter/SectionFooterStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SectionHeader/SectionHeader.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SectionHeader/SectionHeaderStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Trend/Trend.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Trend/TrendStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/TrendImage/TrendImage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/TrendImage/TrendImageStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/_FilterFeedbackBarButton+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/_FilterFeedbackBarButton+View.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Init+Extensions/_FilterFeedbackBarButton+Init.generated.swift
- sourcery/.lib/Sources/utils/Type+Extensions.swift
FilterFeedbackBarButton refactoring in FilterFeedback component
> refactor: 💡 [HCPSDKFIORIUIKIT-2891]FilterFeedbackBarButton

- Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheetStyle.fiori.swift
BannerMultiMessageSheet component supports customization to hide view detail link, or close action.
> fix: 🐛 [JIRA: IOSSDKBUG-548] BannerMultiMessageSheet optimization (#973)

- .github/workflows/pr_only.yml
- Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
New API for background color customization for different rows in ListPickerDestination
Ref: #1003
> fix: 🐛 [IOSSDKBUG-589] background color for destination row

- Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
Ref: #1007 
Missed code reuse.
> fix: 🐛 reuse destination row

- Sources/FioriSwiftUICore/_FioriStyles/PlaceholderTextFieldStyle.fiori.swift
Placeholder visibility has no relation to focus state.
> fix: 🐛 [JIRA:0] PlaceholderTextField enhancement

- Apps/Examples/Examples/FioriSwiftUICore/ToastMessage/ToastMessageExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/ToastMessageStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ToastMessage/ToastMessage.generated.swift
Fixes the default values for the corner radius and icon color, adds documentation and updates the test case
> feat: 🎸 HCPSDKFIORIUIKIT-2920 Add position parameter to Toast Message

- Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMessageModifierExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/AINoticeStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
Modified the icon alignment to the first line of the banner message and AI notice message based on UX review feedback
> fix: 🐛 [JIRA:0] Modified icon alignment of the banner message

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/_DurationPickerExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterView+Extensions.swift
- Sources/FioriSwiftUICore/Components/MultiPropertyComponents.swift
- Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
- Sources/FioriSwiftUICore/DurationPicker/DurationPickerViewWrapper.swift
- Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemContainer.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
- Sources/FioriSwiftUICore/Views/SortFilter/SortFilterCFGItemContainer.swift
- Sources/FioriSwiftUICore/Views/_DurationPicker+View.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/DurationPickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DurationPicker/DurationPicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DurationPicker/DurationPickerStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ToastMessage/ToastMessage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ToastMessage/ToastMessageStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/API/_DurationPicker+API.generated.swift
- Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/_DurationPicker+View.generated.swift
- sourcery/.lib/Sources/utils/Type+Extensions.swift
Duration Picker refactoring.
Add a new type `.durationPicker` into SortFilterItem.
> refactor: 💡 [HCPSDKFIORIUIKIT-2232]SortFilter duration picker

- Apps/Examples/Examples/FioriSwiftUICore/Attachment/MandatoryAttachmentExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Attachment/Attachment.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/AttachmentButtonImage/AttachmentButtonImage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/AttachmentGroup/AttachmentGroup.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/AttachmentThumbnail/AttachmentThumbnail.generated.swift
AttachmentGroup refactor with MandatoryField
> refactor: 💡 [HCPSDKFIORIUIKIT-2927] AttachmentGroup refactor

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/Onboarding/AuthenticationScreenSample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Onboarding/OnboardingExamples.swift
- Sources/FioriSwiftUICore/Utils/FioriOnboardingUtil.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/AuthInputStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/AuthenticationStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/SignInActionStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/AuthInput/AuthInput.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/AuthInput/AuthInputStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Authentication/Authentication.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/Authentication/AuthenticationStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SignInAction/SignInAction.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/SignInAction/SignInActionStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
- Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings
- Tests/FioriSwiftUITests/FioriSwiftUICore/AuthenticationElementTests.swift
Implement the function of Onboarding: Authentication in UIKitSDK.
> feat: 🎸 [HCPSDKFIORIUIKIT-2682]Onboarding: Authentication

- Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TextInputFieldStyle.fiori.swift
Added decimal style for TextInputField
> fix: 🐛 [JIRA:0] Fixed the text input issue for Stepper

- Apps/Examples/Examples/FioriSwiftUICore/KPI/KPIHeaderExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/ObjectHeader/HeaderChartExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/ObjectHeader/ObjectHeaderTestApp.swift
- Apps/Examples/Examples/FioriSwiftUICore/ProfileHeader/ProfileHeaderAnimatableExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/ProfileHeader/ProfileHeaderStaticExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/StepProgressIndicator/StepProgressIndicatorExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Timeline/CustomTimelinePreviewExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/HeaderChartStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/KPIHeaderStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/ObjectHeaderStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/ProfileHeaderStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/TimelinePreviewStyle.fiori.swift
1.Chart Header 
2.Profile Header
3.KPI Header
4.Object Header
5.Timeline Preview
6.Step Progress Indicator (Header element)
7.Banner(Hairline already exists)
> feat: 🎸 [HCPSDKFIORIUIKIT-2926]Add Hairlines to Header components

- Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
Add a filter to prevent users from typing two consecutive decimal points, for example: 6.. and 6.2.3
> fix: 🐛 Add a filter to prevent typing two decimal points

- Apps/Examples/Examples/FioriSwiftUICore/FormViews/FilterFormViewExamples.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/FilterFormViewStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/FilterFormView/FilterFormView.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/FilterFormView/FilterFormViewStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
Support checkmark image customization
> fix: 🐛 [JIRA:0] FilterFormView enhancement

- Apps/Examples/Examples/FioriSwiftUICore/Onboarding/WelcomScreen/OnBoardingWelcomeScreenExamples.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/DateTimePickerExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/DurationPickerExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/ValuePickerExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/DateTimePickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/DurationPickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/ValuePickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePickerStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DurationPicker/DurationPicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DurationPicker/DurationPickerStyle.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ValuePicker/ValuePicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/ValuePicker/ValuePickerStyle.generated.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/DateTimePickerTests.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/DurationPickerTests.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/MasterPickerVisibleBindingTests.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/ValuePickerTests.swift
Dev result
https://github.com/user-attachments/assets/792f3548-2b32-46af-b760-d312fc67ace9
> fix: 🐛 [IOSSDKBUG-706] Request to expose functionality for programmatically collapsing picker components

- Apps/Examples/Examples.xcodeproj/project.pbxproj
- Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarSegmentedControl.swift
Requested by SFSF team to show how to support the navigation bar to include a segmented control under the title. The title should support largeTitle style as well.
The code is all based on iOS API, no Fiori SDK API needed here.
> test: 💍 Create Nav Bar with SegmentedControl and Large Title

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Sources/FioriSwiftUICore/DataTable/DataTable.swift
Fix a DataTable refresh bug reported from Success Factors
> fix: 🐛 fix a DataTable refresh bug

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
- Sources/FioriSwiftUICore/Views/SortFilter/SortFilterCFGItemContainer.swift
Implementation of OrderPicker is updated to 'List', so FilterFeedback and Sort and Filter view need be updated.
> refactor: 💡 [HCPSDKFIORIUIKIT-2891]OrderPicker FilterFeedback and SortFilter

- Sources/FioriSwiftUICore/_FioriStyles/AIUserFeedbackStyle.fiori.swift
Adapt normal view and failed view switch when triggered from writing assistant or other view.
> fix: 🐛 [HCPSDKFIORIUIKIT-2948]AI User Feedback improve2

- Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
- Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
> fix: 🐛 [0]List row background color in filterfeedback dark mode

- Apps/Examples/Examples/FioriSwiftUICore/ToastMessage/ToastMessageExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/ToastMessageStyle.fiori.swift
> fix: 🐛 OSSDKBUG-772 Fix Toast Message UI hang

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
> chore: 🤖 code format

- Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/WritingAssistantFormStyle.fiori.swift
|Before|After|
|-|-|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-07-30 at 10 11 57" src="https://github.com/user-attachments/assets/48a3bc24-e884-4bd5-b9e0-0a72717769bc" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-07-30 at 10 06 52" src="https://github.com/user-attachments/assets/adcbf4bd-e4a1-4b21-beb1-d7cf3867ca84" />|
> fix: 🐛 [IOSSDKBUG-860] update close action style in W.A.

- Sources/FioriSwiftUICore/_generated/StyleableComponents/BannerMessage/BannerMessage.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/CloseAction/CloseAction.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/WritingAssistantForm/WritingAssistantForm.generated.swift
> fix: 🐛 [IOSSDKBUG-845] update generation code by sourcery

- Apps/Examples/Examples/FioriSwiftUICore/FioriButton/FioriButtonContentView.swift
- Sources/FioriSwiftUICore/Utils/EnvironmentValues.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardFooterStyle.fiori.swift
Tests on iOS 17.5
Tests on iOS 18.3.1
> feat: 🎸 add isInMenu environment key and a misc test

- Apps/Examples/Examples/FioriSwiftUICore/FioriButton/FioriButtonContentView.swift
- Sources/FioriSwiftUICore/Utils/EnvironmentValues.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardFooterStyle.fiori.swift
> feat: 🎸 add isInMenu environment key and a misc test;cherrypick

- Apps/Examples/Examples/FioriSwiftUICore/Picker/DateTimePickerExample.swift
- Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
- Sources/FioriSwiftUICore/_FioriStyles/DateTimePickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePicker.generated.swift
- Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePickerStyle.generated.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/DateTimePickerTests.swift
Covert property selectedDate to an optional binding
> fix: 🐛 [IOSSDKBUG-881] DateTimePicker improvement

- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardFooterStyle.fiori.swift
> feat: 🎸 add card footer button width mode [jira: 0]; cherrypick

- Apps/Examples/Examples/FioriSwiftUICore/IllustratedMessage/IllustratedMessageExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/Picker/SegmentedControlExample.swift
- Apps/Examples/Examples/FioriSwiftUICore/SearchBar/SearchFontAndColor.swift
- Apps/Examples/Examples/FioriSwiftUICore/SearchBar/SearchIconAndPlaceholder.swift
- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
- Sources/FioriSwiftUICore/_FioriStyles/SegmentedControlPickerStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/SwitchStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/SwitchViewStyle.fiori.swift
|before|after|iOS 18.5|
|-|-|-|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-26 at 13 44 09" src="https://github.com/user-attachments/assets/d3636412-0ef2-4988-b296-27663c8d9191" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-26 at 13 45 25" src="https://github.com/user-attachments/assets/0f927fc3-a3e8-4bdd-ac76-07ba230a1efa" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-26 at 14 36 05" src="https://github.com/user-attachments/assets/d9a3b2df-a7ef-4733-be35-c8bfb1ba23ee" />|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-26 at 13 49 36" src="https://github.com/user-attachments/assets/fee268ca-f009-4016-ad0f-dd0cd17545 …
> feat: 🎸 [HCPSDKFIORIUIKIT-2999] style upgrade for iOS 26

- Sources/FioriSwiftUICore/Views/Toolbar/FioriToolbar.swift
Remove HStack container and keep items separately.
> fix: 🐛 [HCPSDKFIORIUIKIT-3032] remove HStack from tool bar

- .github/workflows/ci.yml
- .github/workflows/pr_only.yml
- Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
- Makefile
- Sources/FioriSwiftUICore/Views/Carousel.swift
- Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift
New features:
1. add a new Carousel init with itemWidth
2. allow apps to set the initial visible item in the Carousel
Changes:
1. Update ci.yml and pr_only.yml to use macos-15 and Xcode 16.4
Once the a11y focus is changed the Carousel moves to the focused item automatically:
https://github.com/user-attachments/assets/5949dc39-4947-414d-838c-54b1d8832a0c
Snapping:
https://github.com/user-attachments/assets/9e1b554e-7fa1-4089-b61c-b30db23eee8e
> fix: 🐛 Carousel moves to the A11Y focused item automatically [jira: IOSSDKBUG-865]

- Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemContainer.swift
- Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings
Updated the accessibilityLabel of switchItem in FilterFeedbackBar to the meaningful words
> fix: 🐛 [IOSSDKBUG-872] A11y Voice Issue for FilterFeedbackBar

- .github/workflows/ci.yml
- .github/workflows/pr_only.yml
- Makefile
Upgrade build to use Xcode 26.0 so new APIs can be used on main branch
> chore: 🤖 upgrade to Xcode 26.0 for build

- Sources/FioriSwiftUICore/_FioriStyles/ObjectItemStyle.fiori.swift
> fix: 🐛 update title color to primary label

- Apps/Examples/Examples/FioriSwiftUICore/ToolbarExample/ToolbarView.swift
- Sources/FioriSwiftUICore/Views/Toolbar/FioriToolbar.swift
- Tests/FioriSwiftUITests/FioriSwiftUICore/ToolbarTests.swift
Toolbar layout updated for iOS 26, needs more padding and also bug fix for toolbar with helper text
> fix: 🐛 [HCPSDKFIORIUIKIT-3058] toolbar layout calculation error

- Sources/FioriSwiftUICore/_FioriStyles/SectionFooterStyle.fiori.swift
- Sources/FioriSwiftUICore/_FioriStyles/SectionHeaderStyle.fiori.swift
Users feedback that the section header should not have two Traits.
> fix: 🐛 [IOSSDKBUG-864]change section header/footer traits
