.github/configActions/swift-api-assign-reviewer.yml
.github/workflows/pr_only.yml

use GitHub action `swift-api-assign-reviewer` to automatically assign reviewers for pull requests which contain API changes (open/public)

ci: swift-api-assign-reviewer

---

.mailmap

to aliasing authors in Git and resolve duplicate names/emails
without rewriting Git History
Github considers .mailmap file for contributions and it takes time\
to update contributors graph and pulse
Locally use git log --use-mailmap
https://blog.developer.atlassian.com/aliasing-authors-in-git/

chore: add mailmap

---

Apps/FioriSwiftUITestApp/FioriSwiftUITestApp/Examples/SegmentedControl/SegmentedControl+Chart.swift
Sources/FioriSwiftUICore/SegmentedControl/SegmentAttributes.swift
Sources/FioriSwiftUICore/SegmentedControl/SegmentWidthMode.swift
Sources/FioriSwiftUICore/SegmentedControl/SegmentedControl.swift

1. SegmentedControl dynamic height based on content size.
2. Few apis renaming.
3. Add `SegmentWidthMode.equal` mode.
4. Add `allowEmptySelection` api.
5. Bug fixes.

SegmentedControl rework

---

Package.resolved
Package.swift

no code changes in release 1.2.0 it just declares cross-platform support

chore: update dependency "observable-array" to version 1.2.0

---

Apps/Examples/Examples/FioriCharts/ChartsContentView.swift

iOS 14 issue
root cause still under investigation
workaround is to tap different example of same chart type and
then it works

test: fix crash in Examples app when selecting a chart

---

Apps/Examples/Examples/FioriIntegrationCards/IntegrationCardsContentView.swift

to avoid crash when using Xcode 12 to run on iOS 13.x
see https://developer.apple.com/forums/thread/650818

refactor: wrap LazyVGrid in AnyView

---

Apps/Examples/Examples/FioriIntegrationCards/SampleData/InlineTestCases.swift
Sources/FioriIntegrationCards/Components/Common/Header/DefaultHeader.swift
Sources/FioriIntegrationCards/Components/List/UI/ListCardView.swift

in addition fix issue in the header of integration card as status specified with {} placeholder shall be ignored (that's the behavior in web anyway)

add all integration card types in Examples app and fix some Xcode 12 / iOS 14 bugs

---

Apps/Examples/Examples.xcodeproj/project.pbxproj
Apps/Examples/Examples/FioriIntegrationCards/IntegrationCardsContentView.swift
Apps/Examples/Examples/FioriIntegrationCards/SampleData/DataRequestTestCases.swift
Apps/Examples/Examples/FioriIntegrationCards/SampleData/InlineTestCases.swift
Sources/FioriIntegrationCards/Components/Common/Model/Manifest.swift

manifest.json is not stored in directory for baseURL
Example: https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/explore/data
Card Base URL: https://openui5.hana.ondemand.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/
Manifest URL: https://openui5.hana.ondemand.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/samples/data/manifest.json

feat: request data for remote int. card (non-cardBundle)

---

Sources/FioriCharts/Model/ChartModel.swift

The PR contains workaround for compile error for `selectionMode` of the `ChartModel` on Xcode 11. For now it is necessary as downstream projects like `SAPFiori` is based on Xcode 11. As noted in the comment, after Xcode 12 GA this could be removed.

fix: 🐛 compiler error for selectionMode of ChartModel on Xcode 11

---

Apps/Examples/ExamplesTests/SnapshotTests/XCTestCase+Extensions.swift

existing reference images were renamed by
https://github.com/SAP/cloud-sdk-ios-fiori-snapshot-references/pull/4

chore: include recording medium in snapshot reference image file name

---

.github/workflows/recordSnapshotImages.yml

being able to record snapshot reference images (with a specific Xcode and iOS simulator version) and create PR for SAP/cloud-sdk-ios-fiori-snapshot-references via triggering workflow (GitHub action) manually

ci: manual workflow to record snapshot images

---

.github/workflows/ci.yml

GitHub added a new pull_request_target event, which behaves
in an almost identical way to the pull_request event with the
same set of filters and payload. However, instead of running
against the workflow and code from the merge commit, the event
runs against the workflow and code from the base of the pull
request. This means the workflow is running from a trusted source
and is given access to a read/write token as well as secrets
enabling the maintainer to safely comment on or label a pull request.
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

ci: being able to trigger sonar scan for pull requests from forks

---

Sources/FioriSwiftUICore/ColorPalette/Colors/ColorStyle.swift
Sources/FioriSwiftUICore/ColorPalette/PaletteVersion.swift
Sources/FioriSwiftUICore/ColorPalette/Palettes/PaletteV5.swift
Sources/FioriSwiftUICore/ColorPalette/ThemeManager.swift

1. Address naming typos mentioned in Issue #152.
2. Update color palette per GD recommendations.
3. Cached generated dynamic colors per style to reduce new HexColor creations.

refactor: 💡 cache used colors and palette update

---

.github/workflows/ci.yml
.github/workflows/ci_xcode11.yml
.github/workflows/pr_only.yml

- separate different xcode build jobs to avoid issues
- run snapshot tests only if `Sources/**` were changed

ci: improve runtime and avoid issues

---

.github/workflows/recordSnapshotImages.yml

version 0.9 and below were using images (for snapshot testing) generated with Xcode 11.6
Above 0.9 the images recorded will be (per default) with Xcode 12.1

ci: allow to record snapshot images for specific xcode version

---

README.md
Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ActivityItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ActivityItems+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ChartFloorplan+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/CollectionItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ContactItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/HeaderChart+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/KPI+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/KPIAnnotated+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/KeyValueItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectHeader+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ObjectItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ProfileHeader+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SectionHeader+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/TimelineGridItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/TimelineItem+API.generated.swift
sourcery/.lib/Sources/utils/Type+Extensions.swift
sourcery/stencils/main_phase/model_decl_base.swifttemplate
sourcery/stencils/main_phase/noviewbuilderbased_model_decl.swifttemplate
sourcery/stencils/post_phase/composite_model_decl.swifttemplate
sourcery/stencils/pre_phase/component_decl.stencil

being able to add to add (e.g. internal stored) property to generated
ViewModel by using sourcery annotation. Helpful when such property is
needed to implement functionality in extension

chore: 🤖 add property declaration to generated ViewModel

---

Apps/Examples/Examples/FioriSwiftUICore/Experimental/Examples/ContactItemActionItemsExample.swift
README.md
Sources/FioriSwiftUICore/Components/MultiPropertyComponents.swift
Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ContactItem+API.generated.swift
sourcery/.lib/Sources/utils/Array+Variable.swift
sourcery/.lib/Sources/utils/Type+Extensions.swift
sourcery/.lib/Sources/utils/Variable+Extensions.swift
sourcery/stencils/main_phase/model_decl_base.swifttemplate
sourcery/stencils/post_phase/composite_model_decl.swifttemplate
sourcery/stencils/pre_phase/component_decl.stencil

**Previously**: type-based initializer of a composite view was generated that developer passes a view
```swift
public init(.., actionItemsControl: ActivityItems? = nil) {
// ..
}
```
**Now:** type-based initializer of a composite view will be generated that developer passes just the data
```swift
public init(.., actionItems: [ActivityItemDataType]? = nil, didSelectClosure: ((ActivityItemDataType) -> Void)? = nil) {
// ...
}
```
**Changes necessary by contributor**s: move `// sourcery: backingComponent=<Name>` property to the top of the protocol definition
*Previously*
```swift
internal protocol _ActionItems: _ComponentMultiPropGenerating {
// sourcery: no_style
// sourcery: backingComponent=ActivityItems
var actionItems_: [ActivityItemDataType]? { get }
func didSelect(_ activityItem: …
```

chore: 🤖 proper type-based initializer for composite view model

---

.github/workflows/ci_xcode11.yml

different checkout is required for the `pull_request_target` event as otherwise latest updates in PR are not considered
See https://github.com/SAP/cloud-sdk-ios-fiori/pull/215#issuecomment-799844743

chore: use all PR changes in ci_xcode11.yml

---

sourcery/.lib/Sources/utils/Array+Variable.swift

using `// sourcery: customFunctionBuilder=<Name>` had no effect to
optional initializers in <Component>+Init.generated.swift file. This
change ensures that instead of @ViewBuilder the actual @<Name> custom
function builder is used.

chore: 🤖 use customFunctionBuilder in +Init.generated.swift

---

sourcery/stencils/pre_phase/component_decl_environment_key.stencil
sourcery/stencils/pre_phase/component_decl_environment_values.stencil

Generated components should be able to accept a binding of a string (`var aBinding: Binding<String>` == `@Binding var aBinding: String`) but source code generation had a problem determining the correct style type, i.e.  code compilation error as generated EnvironmentKeys/Values for component were using `NothingStyle`)
With this change the following component declaration (please note that the binding is optional)
```swift
import SwiftUI
// sourcery: backingComponent=TextInput
internal protocol _TextInput: _ComponentMultiPropGenerating {
var textFilled_: Binding<String>? { get }
func onCommit() // action handler
}
```
in combination with
```swift
// sourcery: generated_component_not_configurable
public protocol TextInputModel: TextInputComponent {}
```
would result in
```swift
public struct …
```

chore: 🤖 codeGen: Binding<String> to TextStyle

---

README.md
Sources/FioriSwiftUICore/Components/MultiPropertyComponents.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/KPIProgressItem+View.swift
Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
Sources/FioriSwiftUICore/_generated/Components/EnvironmentValues+Styles.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/KPIProgressItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/KPIProgressItem+View.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Init+Extensions/KPIProgressItem+Init.generated.swift
sourcery/.lib/Sources/utils/Array+Variable.swift
sourcery/.lib/Sources/utils/Type+Extensions.swift
sourcery/.lib/Sources/utils/Variable+Extensions.swift
sourcery/README.md
sourcery/stencils/main_phase/model_decl_base.swifttemplate
sourcery/stencils/pre_phase/component_decl.stencil
sourcery/stencils/pre_phase/component_decl_environment_key.stencil
sourcery/stencils/pre_phase/component_decl_environment_values.stencil

Use sourcery annotation `// sourcery: no_view` on a property which shall not be represented as a view. The property will still be used in the initializers but does not have the @ViewBuilder property wrapper and is declared with its original data type.
```swift
internal protocol _KpiProgress: KpiComponent, _ComponentMultiPropGenerating {
// sourcery: no_view
var fraction_: Double? { get }
}
```
Result:
```swift
public struct KPIProgressItem<Kpi: View, Subtitle: View, Footnote: View> { // no `Fraction: View` !
@Environment(\.kpiModifier) private var kpiModifier
@Environment(\.subtitleModifier) private var subtitleModifier
@Environment(\.footnoteModifier) private var footnoteModifier
private let _kpi: Kpi
private let _fraction: Double? // data type is used!
private let _subtitle: Subtitle …
```

chore: codeGen for comp. property not representable as view (no_view)

---

sourcery/.lib/Sources/utils/Variable+Extensions.swift

Fix to apply backingComponent type properly if property data type is `[String]?` or `String` / `Image`
Assuming:
```swift
// sourcery: no_style
// sourcery: backingComponent=TagStack
let tags_: [String]?
```
Correct:
```swift
self._tags = tags != nil ? ViewBuilder.buildEither(first: Tag(tags: tags)) : ViewBuilder.buildEither(second: EmptyView())
```
Incorrect:
```swift
self._tags = tags != nil ? ViewBuilder.buildEither(first: Text(tags.joined(separator: “, “))) : ViewBuilder.buildEither(second: EmptyView())
```

chore: apply backingComponent type also for String, [String] or Image

---

Sources/FioriSwiftUICore/_generated/ViewModels/API/ProfileHeader+API.generated.swift
sourcery/.lib/Sources/utils/Type+Extensions.swift

Fixes the issue that `// sourcery: add_view_builder_params = “detailContent”` still generates `private let _detailContent: DetailContent` while other properties are internal (since https://github.com/SAP/cloud-sdk-ios-fiori/pull/243)

chore: 🤖 change add_view_builder_params from private to internal

---

Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
Sources/FioriSwiftUICore/SignatureView/DrawingPad.swift
Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
Sources/FioriSwiftUICore/SignatureView/SignatureView.swift
Tests/FioriSwiftUITests/FioriSwiftUICore/SignatureCaptureViewTests.swift

Developer may display an existing signature and user can re-sign
BREAKING CHANGE: 🧨 remove onCancel in constructor

fix: 🐛 allows displaying a existing signature image

---

Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift

The background of the RoundedRectangle in SignatureCaptureView should be
clearwhen displaying signature image

fix: 🐛 the background should be clear when displaying signature

---

Sources/FioriSwiftUICore/SignatureView/DrawingPad.swift
Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift
Sources/FioriSwiftUICore/SignatureView/SignatureView.swift
Tests/FioriSwiftUITests/FioriSwiftUICore/SignatureCaptureViewTests.swift

Remove 2 binding vars not needed in DrawingPad

refactor: 💡 remove redundant uiimage vars in DrawingPad

---

.jazzy.yaml
CHANGELOG.md
jazzy/Overview_README.md

After merging this commit we should tag commit with 1.0.0 and create a respective 1.0.0 release
No API documentation for `FioriSwiftUICore` and `FioriThemeManager` yet as too many symbols are not yet properly documented

chore: 🤖 1.0.0 release

---

Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView.swift

1. The current implementation has no xmark and signature line in the default state while the spec has.
2. The current implementation the xmark and signature line are center aligned in the middle while in the spec they are bottom aligned.
3. The current implementation the xmark and signature line color are not matching the spec in the active state.

fix: 🐛 SignatureCaptureView xmark and line matching spec

---

Sources/FioriCharts/Charts/Common/GridLinesAndChartView.swift
Sources/FioriCharts/Charts/Common/XYAxisChart.swift
Sources/FioriCharts/Model/ChartModel.swift

the root cause is iOS Widget view has to be pure swiftui view. but the chart uses a few ui gesture recognizers from UIKit since gestures from swiftui are not powerful enough. Because iOS Widget doesn’t need to support user interaction so it is fine to turn off those part of code.

fix: 🐛 support chart for iOS Widget

---

Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SignatureCaptureView+API.generated.swift

✅ Closes: part of BCP 2170239589

feat: 🎸 Signature: new APIs to hide xmark and underline

---

Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
Sources/FioriSwiftUICore/SignatureView/ScribbleView.swift
Sources/FioriSwiftUICore/SignatureView/SignatureCaptureView+API.generated.swift
Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift

Fix stroke not smooth problem when stroke width is large and 2 new APIs
to hide X mark and signature line
Cherry-picked from main

fix: 🐛 stroke not smooth problem and 2 new APIs

---

Package.resolved
Package.swift

It was not possible to specify dependency for `FioriSwiftUI` package
with `upToNextMajor(from:)` or `upToNextMinor(from:)` due to the use of
commit-based requirement for Zip dependency. Switching to a stable fork
in Package.swift will fix that.

fix: 🐛 use FioriSwiftUI package with version-based requirement

---

Sources/FioriThemeManager/Colors/HexColor.swift

I spoke with Flash over the color issue. Apparently the elevated trait is a [dark mode concept from a design perspective](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode). Which is why there isn’t a light mode color for it. **However it seems as though the system can have scenarios where dark mode is false and elevated is true.** Such as when a modal is presented in light mode.
If the color does not have a value for the variant it defaults to different values.
How we currently handle that is all the color variants are given the value of `darkColor` which is used for Light Mode seen [here](https://github.com/SAP/cloud-sdk-ios-fiori/blob/801ce943d29c0265c023d5320e3755dfa3b877d9/Sources/FioriThemeManager/Colors/HexColor.swift#L34).
As you can see …

fix: 🐛 [BCP: 2280078347] Fix color for high constrast, elevated

---

.jazzy.yaml
jazzy/FioriThemeManager_README.md
jazzy/Overview_README.md
scripts/generateDocumentation.sh

API Documentation was not build to due ambiguous destination.
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:0[9](https://github.com/SAP/cloud-sdk-ios-fiori/runs/4513325548?check_suite_focus=true#step:4:9)4DB82D-7F2E-4111-89F3-D963B3A066C8, OS:15.0, name:iPad (7th generation) }
{ platform:iOS Simulator, id:EBD0871A-A099-47CC-905E-A9CFA7BA6D7D, OS:15.0, name:iPad (8th generation) }
{ platform:iOS Simulator, id:28003E16-EB1E-440C-B9FD-7044F17DFD95, OS:15.0, name:iPad (9th generation) }
{ platform:iOS Simulator, id:A45049DA-374D-4300-9124-70A603CFEF0C, OS:15.0, name:iPad Air (3rd generation) }
{ …
```

API Reference: ensure building and add FioriThemeManager

---

Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/SignatureView/ScribbleView.swift
Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SignatureCaptureView+API.generated.swift

The saved signature can now be display in both light and dark modes
Similar changes to the FUISignatureCaptureController

fix: 🐛 [BCP:0] SignatureCaptureView display image color issue

---

Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift

no truncation for long key name
✅ Closes: [JIRA:HCPSDKFIORIUIKIT-2158]
(cherry picked from commit b6bf20e531bc460bf632536b4354b1c2caab3106)

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2158] InlineSignatureFormCell (#455)

---

Sources/FioriThemeManager/ThemeManager.swift

Before this fix, setting a custom palette
```swift
ThemeManager.shared.setPalette(aCustomPalette)
```
caused a crash when calling `Color.preferredColor(_:background:interface:display:)` because
```swift
internal func color(for style: ColorStyle, background scheme: BackgroundColorScheme?, interface level: InterfaceLevel?, display mode: ColorDisplayMode?) -> Color {
let uiColor = self.uiColor(for: style, background: scheme, interface: level, display: mode) // <== returned UIPlaceholderColor
let color = Color(uiColor)
return color
}
```

fix: 🐛 fix crash when using custom palette

---

Apps/Examples/Examples.xcodeproj/project.pbxproj
Apps/Examples/Examples/ContentView.swift
Apps/Examples/Examples/FioriThemeManager/Colors.swift
Apps/Examples/Examples/FioriThemeManager/FioriThemeManagerContentView.swift
Apps/Examples/Examples/LazyView.swift
Package.swift
README.md
Sources/FioriThemeManager/Colors/Color+Extension.swift
Sources/FioriThemeManager/Colors/ColorStyle.swift
Sources/FioriThemeManager/StyleSheet/Internal/StyleSheet.swift
Sources/FioriThemeManager/StyleSheet/Internal/StyleSheetConverter.swift
Sources/FioriThemeManager/StyleSheet/Internal/StyleSheetParser.swift
Sources/FioriThemeManager/StyleSheet/StyleSheetSettings.swift
Sources/FioriThemeManager/ThemeManager.swift
Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetConverterTests.swift
Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetParserTests.swift
Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetSettingsIntegrationTests.swift
Tests/FioriSwiftUITests/FioriThemeManager/TestResources/styleSheet.nss
Tests/FioriSwiftUITests/FioriThemeManager/ThemeManagerTests.swift
jazzy/FioriThemeManager_README.md

This PR introduces the possibility to **override the color definitions of an existing color palette** in two ways
- programmatically
```Swift
ThemeManager.shared.setColor(.red, for: .primaryLabel, variant: .light)
// or
ThemeManager.shared.setHexColor("FF0000", for: .primaryLabel, variant: .light)
```
- through a style sheet
```Swift
var colorOverrides = """
@primaryLabel:#FF6000;
@primaryLabel_darkBackground:#00FFFF;
"""
try? StyleSheetSettings.loadStylesheetByString(content: colorOverrides)
// or use static StyleSheetSettings.loadStylesheetByURL(url:) to load from a local file
```
Related to this new functionality the PR includes
- documentation for `FioriThemeManager` module
- integration tests
- programming and style sheet usage examples in ExamplesApp …

feat: 🎸 override color definitions (e.g. through style sheet)

---

Sources/FioriThemeManager/Colors/ColorStyle.swift

Moving extension into compiler directive for easier consumption internally. No code change or impact for this Swift Package.

chore: 🤖 exclude ColorStyle extension for SAPFiori target

---

.github/workflows/ci.yml
.github/workflows/dependencyManagement.yml
.github/workflows/jazzy.yml
.github/workflows/pr_only.yml
.github/workflows/rebase.yml
.github/workflows/recordSnapshotImages.yml
.github/workflows/release.yml
.github/workflows/tooling.yml
.github/workflows/xcframeworks.yml

actions/checkout@v2 uses Node.js 12 which is deprecated
actions/checkout@v3 uses Node.js 16
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for more details.
Command to replace in all yml files:
`find . -type f -name "*.yml" -print0 | xargs -0 sed -i '' -e 's/actions\/checkout@v2/actions\/checkout@v3/g'`

ci: use actions/checkout@v3

---

CHANGELOG.md

Omitted `sizeThatFits` feature that was added to mainly support auto-sizing chart card in UIKit and is not supposed to be used by SwiftUI consumers.
I will create tag and GitHub release for 3.0.1 once merged into `main` branch

chore: 🤖 3.0.1

---

Apps/Examples/Examples/FioriSwiftUICore/DataTable/DataTableExample.swift
Sources/FioriSwiftUICore/DataTable/DataTable.swift
Sources/FioriSwiftUICore/DataTable/ItemView.swift

fix: 🐛 [BCP: 2270182630] fix tap on white space in DataTable

---

Apps/Examples/Examples.xcodeproj/project.pbxproj
Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPicker.swift
Apps/Examples/Examples/FioriSwiftUICore/FormCells/SearchableListViewExample.swift
Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift

Support single selection and allow empty filter condition.
https://user-images.githubusercontent.com/2142582/202390450-9ab3ba2c-c5e6-4de7-b64a-5c8e9bc177ba.mp4

feat: 🎸 [JIRA: 2219] List picker with single selection

---

Sources/FioriSwiftUICore/Views/SearchableListView+View.swift

Without updates, selection should not be cleared.

fix: 🐛 searchable list selection handler

---

Sources/FioriSwiftUICore/DurationPicker/DurationPickerViewWrapper.swift

|before|after|
|-|-|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-13 at 11 26 01](https://user-images.githubusercontent.com/2142582/218380959-4b269d40-9593-4ba2-874f-2bab7e890901.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-13 at 11 24 53](https://user-images.githubusercontent.com/2142582/218380982-a6e9e11d-eb66-4b30-b368-e3ccad5a8bdd.png)|

fix: 🐛 duration picker layout for rtl

---

Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift

Use 72 font for SignatureCaptureView
✅ Closes: HCPSDKFIORIUIKIT-2247

fix: 🐛 [JIRA:HCPSDKFIORIUIKIT-2247] SignatureCaptureView font

---

Mintfile

PR workflow fails when running code formatting as `mint bootstrap` will try to install tools specified in `Mintfile` but the tool `sourcery` with its version 1.1.1 can no longer be resolved by SPM
The easiest fix for this CI issue is to update sourcery version in `Mintfile`.
Note: I have not re-generated files generated by sourcery so if people run `mint bootstrap` locally and re-generate files then at least the headers for touched files would change.
FYI: An alternative would be to change the workflow to run `mint install nicklockwood/SwiftFormat@0.47.3` only but then two files would need to change if we decide to use a different version of SwiftFormat so I do not favor that alternative.

fix PR workflow which fails for CodeFormattingCheck

---

.github/workflows/ci.yml
README.md

pull_request_target as a trigger condition was introduced for being able to trigger sonar scan for pull requests from forks but  we don't make much use of this and using pul_request_target has disadvantages as the workflow runs against the base  of the pull request which can cause issues
Plus minor other changes

ci: 🎡 remove pull_request_target as trigger condition

---

Sources/FioriThemeManager/ThemeManager.swift
Tests/FioriSwiftUITests/FioriThemeManager/StyleSheetParserTests.swift
Tests/FioriSwiftUITests/FioriThemeManager/TestResources/BCP2370020386.nss

Problem was found in processing input parameters mapping to variant.
Fix is to add cases of switch statement for the missing cases.

fix: incorrect color value for the elevatedContrastLight variant

---

Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift

Dismiss keyboard when user start signing
BREAKING CHANGE: 🧨 no
✅ Closes: BCP:2370041675

fix: 🐛 [BCP:2370041675] dismiss keyboard when signing

---

Sources/FioriSwiftUICore/DataTable/ItemView.swift
scripts/githooks/pre-commit

update pre-commit to sync up with CI job, also one swift file whose format was overridden by a previous commit
BREAKING CHANGE: 🧨 No

chore: 🤖 update pre-commit to sync up with CI job

---

Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
Sources/FioriSwiftUICore/Views/Action+View.swift
Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

fix: 🐛 [BCP:2370082757] Fix SignatureCaptureView VO issues

---

Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+Style.swift

|FilterFeedbackBar(Light)|FilterFeedbackBar(Dark)|
|----|----|
|<img width="350" alt="light" src="https://github.com/SAP/cloud-sdk-ios-fiori/assets/149659707/61545be0-3ae1-4432-8660-37177d9b7ffe">|<img width="353" alt="dark" src="https://github.com/SAP/cloud-sdk-ios-fiori/assets/149659707/ee1bb1d2-f3a3-45f8-8eb7-7a7022624b5c">|
feat: [JIRA:HCPSDKFIORIUIKIT-2540] Color updates for Filter Feedback Bar - SwiftUI

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2540] Filter Feedback

---

Package.swift

I observed this issue when trying to use FioriSwiftUI package in a framework and using FioriSwiftUI umbrella library. The framework, when compiling for MacCatalyst, complains for `import FioriThemeManager`.
The conditional target handling, introduced for supporting visionOS, requires us to specify the macCatalyst platform. A regression issue but no customer noticed that because we didn't create a new release yet.

chore: make required modules for FioriSwiftUI target/library also available for MacCatalyst

---

Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPicker.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ListPickerItem+API.generated.swift

Jira: IOSSDKBUG-156 SwiftUI ListPickerItem can't add toolbar
`.listPickerListStyle` is changed to a new one to support customization for destination list in list picker..
|before|after|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-25 at 15 58 44](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/83f482a4-a23d-481e-86ec-6fde1bd8e6d8)|![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-25 at 15 57 51](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/f937fdce-16d0-491d-b3ae-4511274cc215)|

feat: 🎸 list picker enhancement

---

Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarCustomItem.swift
Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarExample.swift
Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarFioriStyle.swift
Apps/Examples/Examples/FioriSwiftUICore/NavigationBar/NavigationBarPopover.swift

|1|2|3|
|-|-|-|
|![image](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/42176493-e258-41ce-8dc0-2a7d5e2066ad)|![image (1)](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/ced33e48-da82-4e4b-bc1f-c6104eb53749)|![image (2)](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/71105780-9f9d-4371-87f8-e463cbfe9a25)|

fix: 🐛 update navigation bar style

---

Apps/Examples/Examples/FioriSwiftUICore/SideBar/EditableSideBarExample.swift
Sources/FioriSwiftUICore/_FioriStyles/SideBarListItemStyle.fiori.swift

Issue description: Found an issue in SideBar to support the customization during wrapper this control in UIkit FUISideBar control. The issue was that to customize the selected item via the individual control's style can't work. E,g, To customize the title's color, font for a selected item via .titleStyle can NOT work. Same issue on subtitle, icon and accessoryIcon.
This PR handle the fix for the issue and also add the demo case for this scenario.

fix: 🐛 fix customization supporting issue in SideBar

---

Sources/FioriSwiftUICore/Utils/Bundle+Extensions.swift

Inspiration from https://forums.swift.org/t/unable-to-find-bundle-in-package-target-tests-when-package-depends-on-another-package-containing-resources-accessed-via-bundle-module/43974/5

chore: 🤖 fix fatalError when running tests of a package that relies on FioriSwiftUI package

---

Apps/Examples/Examples/FioriSwiftUICore/ProfileHeader/ProfileHeaderStaticExample.swift
Sources/FioriSwiftUICore/_FioriStyles/ProfileHeaderStyle.fiori.swift

1. Update subtitle style to headline font with secondaryLabel color.
2. Add missed title color.
3. Add a picker to switch detail content between fiori button and icons stack.

fix: 🐛 [JIRA: HCPSDKFIORIUIKIT-1940] profile header style

---

Sources/FioriSwiftUICore/_FioriStyles/SideBarListItemStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/SideBarStyle.fiori.swift

This PR addresses the issue concerning the image size used in the UIKit Sidebar, a problem discovered while implementing UX designer enhancements.
In the UIKit Sidebar, an SWiftUI Image converted from UIImage is employed. Originally, the code attempted to use the .resizable modifier to allow the image to resize and maintain a default size. Unfortunately, this approach was ineffective as the image continuously displayed at an incorrect size. After consulting with Xiao-Yu, it became evident that the placement of a frame around the image was erroneous. To rectify this, we should avoid setting a frame and instead, designate a suitable font size to maintain the image’s default dimensions. Additionally, this modification ensures support for larger accessibility sizes. With this fix, there is no …

fix: 🐛 Fix Image size issue on SideBar

---

Sources/FioriSwiftUICore/_FioriStyles/SideBarStyle.fiori.swift

This PR addresses the issue concerning the scrolling in the UIKit Sidebar, a problem discovered while implementing UX designer enhancements.
The issue was with the Sidebar as the content of primary view in the UISplitViewController. When setting a `.background` modifier on a `ScrollView` or outside of it within the SwiftUI Sidebar, the primary view in the UISplitViewController could not be scrolled vertically and only the 'SideBar' control was scrolled vertically. After testing, I found that moving the `.background` modifier inside the `ScrollView` resolves the problem for the UIKit Sidebar.

fix: 🐛 Fix scroll issue on SideBar

---

.github/workflows/ci.yml
Makefile

Changes to build & test for visionOS when GitHub action is triggered by PR/commit
Helps to avoid that code changes will be merged that would not compile on visionOS

ci: build & test for visionOS

---

CHANGELOG.md
Sources/FioriSwiftUICore/_FioriStyles/JouleWelcomeScreenStyle.fiori.swift

Adding default JMC welcome screen background color so that the legal disclaimer's background color matches conversation scroll view's background color.
After adding background color
Before adding background color

fix: IOSSDKBUG-282 - JMC welcome screen legal disclaimer bg color

---

Sources/FioriSwiftUICore/DataTable/LayoutData.swift

All columns left and right padding are same according to regular or compact by default.
Developers can set 'dataCellPadding' to custom the padding.

fix: 🐛 [JIRA:IOSSDKBUG-264] No left padding for the 1st column in DataTable

---

Sources/FioriSwiftUICore/Views/Toolbar/FioriToolbar.swift

Use `@StateObject` to make sure the only true source of handler.
|before|after|
|-|-|
|<img width="240" alt="Screenshot 2024-08-13 at 10 55 09" src="https://github.com/user-attachments/assets/607b06e3-c6ed-4401-9bf0-3a9efbcb1ca7">|<img width="242" alt="Screenshot 2024-08-13 at 10 54 39" src="https://github.com/user-attachments/assets/ea97acf1-5eb9-4eb5-a244-d35d2f916a76">|
Test Code
```swift
#Preview {
TestView()
}
class TestViewModel: ObservableObject {
@Published var isScreenLoading = false
}
struct TestView: View {
@StateObject var viewModel = TestViewModel()
var body: some View {
NavigationStack {
Text("Hello world.")
.fioriToolbar {
FioriButton { _ in
self.viewModel.isScreenLoading = true
} label: { _ in
Text("Change value")
.frame(maxWidth: .infinity)
}
}
}
}
}
```

fix: 🐛 [JIRA: IOSSDKBUG-306] toolbar layout issue

---

Apps/Examples/Examples/FioriSwiftUICore/IllustratedMessage/IllustratedMessageExample.swift
Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/IllustratedMessage/IllustratedMessage.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/IllustratedMessage/IllustratedMessageStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2702]Illustrated Message Enhancement

---

Apps/Examples/Examples/FioriSwiftUICore/FormViews/KeyValueFormViewExample.swift
Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift

fix: 🐛 [JIRA:IOSSDKBUG-324]Usage of SwiftUI KeyValueFormView

---

Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/RatingControlStyle.fiori.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

✅ Closes: JIRA:HCPSDKFIORIUIKIT-2707

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2707]RatingControl: accessibility updates

---

Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/FilterFeedbackBarButton+View.swift
Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/OptionListPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Model+Extensions/OptionListPickerItemModel+Extensions.generated.swift

FilterFeedbackBar picker sheet enhancement, custom item layout
support fixed and flexible layout, default fixed

feat: 🎸 [JIRA:IOSSDKBUG-347] FilterFeedbackBar picker enhance

---

Apps/Examples/Examples/FioriSwiftUICore/Picker/DateTimePickerExample.swift
Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
Sources/FioriSwiftUICore/_FioriStyles/DateTimePickerStyle.fiori.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePicker.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/DateTimePicker/DateTimePickerStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/StyleConfiguration+Extension.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

Add Mandatory Field Styling for DateTimePicker. Add controlState for disable/readonly state. Add informationView for the error/hint message.

feat: 🎸 HCPSDKFIORIUIKIT-2718 Mandatory Field for DateTimePicker

---

Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPicker.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Utils/FioriVStack.swift
Sources/FioriSwiftUICore/Views/KeyValueItem+View.swift
Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/ListPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Init+Extensions/ListPickerItem+Init.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Model+Extensions/ListPickerItemModel+Extensions.generated.swift

Add vertical layout support for key-value  and font style update.
|vertical|disabled|
|-|-|
|![Simulator Screenshot - iPhone 16 Pro Max - 2024-09-19 at 14 28 11](https://github.com/user-attachments/assets/8d2ed62a-59e6-4aac-adb0-bcf8f8d5e3f7)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-09-19 at 14 28 13](https://github.com/user-attachments/assets/cef0aba9-f82f-4e06-8d2b-f282fad9563a)|

fix: 🐛 [JIRA: 0] list picker item styles issue

---

Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift

.popover can be anchored correctly by iOS automatically.
So, there is no need to use the property "attachmentAnchor: .point(.bottom)"
After fix for iOS 18 and 17 (iPad):

fix: 🐛 IOSSDKBUG-416 FilterFeedbackBar not anchored correctly

---

Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/OptionListPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchListPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchableListView+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/SearchListPickerItem+View.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Model+Extensions/SearchListPickerItemModel+Extensions.generated.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

Sort & Filter Enhancement Part 2. Cherry-pick from main.

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2766]Sort & Filter Enhancement 2

---

Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift

Fix FilterFeedbackBar popover view layout on iPad and Vision Pro.

fix: 🐛 [IOSSDKBUG-416]Fix FilterFeedbackBar layout on iPad

---

Apps/Examples/Examples/FioriSwiftUICore/FormViews/KeyValueFormViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/FormViews/NoteFormViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/FormViews/TextFieldFormViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/FormViews/TitleFormViewExample.swift
Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TextFieldFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TextInputInfoViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TitleFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

1. Fixes the mandatory indicator color problem.
2. Fixes a11y problem with NoteFormView, KeyValueFormView, and, TitleFormView.
3. For TextFieldFormView, the fix is not completed yet. There is still problem when alternative action button is present.
Note that the TextField and TextEditor is always read by VoiceOver no matter the order it is on the FormView. I think this is a SwiftUI behavior. We can change the order for UIKit but not SwiftUI. I believe this is a SwiftUI behavior.

fix: 🐛 [JIRA:IOSSDKBUG-375] TextInput Fom View a11y fixes 1

---

Apps/Examples/Examples/FioriSwiftUICore/FormCells/StepperViewExample.swift
Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TextInputFieldStyle.fiori.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperField/StepperField.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperField/StepperFieldStyle.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperView/StepperView.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/StepperView/StepperViewStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/StyleConfiguration+Extension.generated.swift

Cherry pick from main branch.
feat: 🎸 [HCPSDKFIORIUIKIT-2791]SwiftUI: floating value support (https://github.com/SAP/cloud-sdk-ios-fiori/pull/834)

feat: 🎸 [HCPSDKFIORIUIKIT-2791]SwiftUI: floating value support (Cherry-pick)

---

Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchListPickerItem+API.generated.swift

Fix listpicker and popover height in filterFeedbackBar when keyboard is shown.

fix: 🐛  [HCPSDKFIORIUIKIT-2766] sort & filter enhancement list pick search

---

Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchListPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

Add 'ListEntriesSectionMode' to control whether entries section shown or not.
when listEntriesSectionMode is 'default', depends on 'allowsMultipleSelection', when allowsMultipleSelection is true, selections should be shown in an individual section.

feat: 🎸 [JIRA:IOSSDKBUG-434] filterFeedBack list mutil selections shown in section

---

Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift

Fix popover arrow direction on 17 iPad when 'displayMode' is '.filterFormCell'.

fix: 🐛 [IOSSDKBUG-416]FilterFeedbackBar on 17 iPad layout

---

Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/SortFilterView+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift

Fix datePicker layout on visionOS, and adjust configuration layout size.

fix: 🐛 [IOSSDKBUG-416]FilterFeedBackBar layout

---

Apps/Examples/Examples/FioriSwiftUICore/KPI/KPIProgressViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/KPI/KPIViewExample.swift
Sources/FioriSwiftUICore/Toast/ToastView.swift
Sources/FioriSwiftUICore/Views/_ObjectItem+View.swift

[HCPSDKFIORIUIKIT-2828](https://jira.tools.sap/browse/HCPSDKFIORIUIKIT-2828) PreviewDevice is ignored in a #Preview macro
This PR handle the change to clean up the warning message 'PreviewDevice is ignored in a #Preview macro' with XCode 16.1. 
See the following [Xcode 15 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Previews):
_**The preview canvas has a new control for picking which device to use for previewing. By default it tracks the device family of the selected run destination, but a specific device can be selected. This should be used in favor of the previewDevice modifier.**_
Therefore, going forward, the `previewDevice` modifier should not be used. Instead, the control on the canvas GUI should be used to select a preview …

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2828] PreviewDevice is ignored in a #Preview macro

---

Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/SortFilterItemTitle.swift

Improve space between list view and apply button.
And update the font of elements in navigation bar.

fix: 🐛 [IOSSDKBUG-449]FilterFeedbackBar list apply space

---

Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchListPickerItem+API.generated.swift

Calculate popover height based on bar item position.
Set `arrowEdge` based on bar item position. Only `.top` or '.bottom' will be set. Condition is item's position above or below half screen height.

fix: 🐛 [IOSSDKBUG-480]Popover view height on iPad

---

Apps/Examples/Examples.xcodeproj/project.pbxproj
Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
Apps/Examples/Examples/FioriSwiftUICore/Indicator/ProcessingIndicatorExample.swift
README.md
Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
Sources/FioriSwiftUICore/_FioriStyles/ProcessingIndicatorStyle.fiori.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/ProcessingIndicator/ProcessingIndicator.generated.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/ProcessingIndicator/ProcessingIndicatorStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ModifiedStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/View+Extension_.generated.swift
Sources/FioriSwiftUICore/_generated/SupportingFiles/ViewEmptyChecking+Extension.generated.swift

feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2806] Processing Indicator

---

Sources/FioriSwiftUICore/DataTable/DataTable.swift
Sources/FioriSwiftUICore/DataTable/InlineEditingView.swift
Sources/FioriSwiftUICore/DataTable/ItemView.swift
Sources/FioriSwiftUICore/Experimental/Popover/PopoverModifier.swift
Sources/FioriSwiftUICore/Toast/ToastView.swift
Sources/FioriSwiftUICore/Utils/View+Extensions.swift
Sources/FioriSwiftUICore/Views/SearchableListContent.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepProgressIndicator+View.swift
Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheetStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/CheckoutIndicatorStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/DateTimePickerStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/ProgressIndicatorStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/StepperFieldStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TextFieldFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TextInputFieldStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/TitleFormViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/ToastMessageStyle.fiori.swift

'onChange(of:perform:)' was deprecated in iOS 17.0: Use `onChange` with a two or zero parameter action closure instead.
✅ Closes: HCPSDKFIORIUIKIT-2840

fix: 🐛 [JIRA:HCPSDKFIORIUIKIT-2840] fix onChange deprecated

---

Sources/FioriThemeManager/ColorCompatibilityMap/ColorCompatibilityMapV4.swift
Sources/FioriThemeManager/ColorCompatibilityMap/ColorCompatibilityMapV5.swift
Sources/FioriThemeManager/Palettes/PaletteV2.swift
Sources/FioriThemeManager/Palettes/PaletteV3.swift
Sources/FioriThemeManager/Palettes/PaletteV4.swift
Sources/FioriThemeManager/Palettes/PaletteV5.swift

There are lots of warnings from old Palette related files ( V2 , V3, V4, V5 ), since some of the color styles were deprecated.
Added the "@available" annotation in related files to tell the compiler to ignore these warnings.
Before the fix :
Showing All Issues
/github/cloud-sdk-ios-fiori/Sources/FioriThemeManager/ColorCompatibilityMap/ColorCompatibilityMapV4.swift:14:25: 'primary1' is deprecated: renamed to 'primaryLabel'
/github/cloud-sdk-ios-fiori/Sources/FioriThemeManager/ColorCompatibilityMap/ColorCompatibilityMapV4.swift:15:27: 'primary2' is deprecated: renamed to 'secondaryLabel'
/github/cloud-sdk-ios-fiori/Sources/FioriThemeManager/ColorCompatibilityMap/ColorCompatibilityMapV4.swift:16:26: 'primary3' is deprecated: renamed to 'tertiaryLabel' …

feat: 🎸 JIRA-2846 ignore warnings from old color palettes

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Sources/FioriSwiftUICore/Views/Carousel.swift

Avoid going to the detail view during dragging a carousel in Joule

fix: 🐛 avoid conflict btw drag and tap gesture in Carousel

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Sources/FioriSwiftUICore/Views/Carousel.swift

improve Carousel's drag gesture to avoid conflicts btw a carousel's horizontal scrolling and the parent scrollview's vertical scrolling
https://github.com/user-attachments/assets/005e26ac-12c9-4c1e-850c-dbff10d43489

fix: 🐛 improve Carousel's drag gesture to avoid conflicts

---

Apps/Examples/Examples/FioriSwiftUICore/Slider/SliderExample.swift
Sources/FioriSwiftUICore/_FioriStyles/RangeSliderControlStyle.fiori.swift

[IOSSDKBUG-530](https://jira.tools.sap/browse/IOSSDKBUG-530): Range Slider the slider overlay the text
This PR addresses the issue where the start and end x-coordinates of the slider's active track are incorrect when the lower or upper value falls below the range's lower bound. Actually, the effective lower and upper values should not exceed the specified lower and upper bounds of the range to ensure that the track displays correctly.
To update the demo case to allow for testing of this scenario.

fix: 🐛 [IOSSDKBUG-530]Range Slider the slider overlay the text

---

Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/SearchListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
Sources/FioriSwiftUICore/Views/SortFilter/_FilterFeedbackBarItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/_SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/SearchListPickerItem+API.generated.swift

When options for the list have duplicated names, distinguish selected name by adding UUID as key and name as value.

fix: 🐛 [IOSSDKBUG-547]FilterFeedbackBar list duplicated names

---

Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageCustomInitExample.swift
Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageExample.swift
Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
Apps/Examples/Examples/FioriSwiftUICore/FormCells/StepperViewExample.swift
Apps/Examples/Examples/FioriSwiftUICore/MenuSelection/MenuSelectionExample.swift
Apps/Examples/Examples/FioriSwiftUICore/StepProgressIndicator/SPIModelExample.swift
Apps/Examples/Examples/FioriSwiftUICore/StepProgressIndicator/StepProgressIndicatorExample.swift
Sources/FioriSwiftUICore/Views/OptionListPickerItem+View.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
Sources/FioriSwiftUICore/Views/SortFilter/_FilterFeedbackBarItem+View.swift

'onChange(of:perform:)' was deprecated in iOS 17.0: Use `onChange` with a two or zero parameter action closure instead.

chore: 🤖 [HCPSDKFIORIUIKIT-2862]warning cleanup

---

Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift

When isTrackingLiveChanges is true, selections should be used for data tracking but not selectionsPool.

fix: 🐛 [IOSSDKBUG-585] list picker destination crash

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift

feat: 🎸 [HCPSDKFIORIUIKIT-2896]Card Insert Custom Component

---

Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
Sources/FioriSwiftUICore/Views/_SliderPickerItem+View.swift
Sources/FioriSwiftUICore/_generated/ViewModels/API/_SliderPickerItem+API.generated.swift
Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/_SliderPickerItem+View.generated.swift
sourcery/.lib/Sources/utils/Type+Extensions.swift

[HCPSDKFIORIUIKIT-2893](https://jira.tools.sap/browse/HCPSDKFIORIUIKIT-2893): SwiftUI code refactoring with component style: SliderPickerItemModel
This PR address the code refactoring for SliderPickerItemModel deprecation. Currently, the styled component FioriSlider was available. The FilterFeedbackBar already use new styled component FioriSlider. The original SliderPickerItemModel can be deprecated.

refactor: 💡 [HCPSDKFIORIUIKIT-2893] SliderPickerItemModel

---

Sources/FioriSwiftUICore/_FioriStyles/ObjectItemStyle.fiori.swift

Use empty view for footnote and icons. Then VStack will handle the spacing automatically. And remove unnecessary bottom padding for footnote and icons.

fix: 🐛 remove extra vertical spacing in object item

---

Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageCustomInitExample.swift
Apps/Examples/Examples/FioriSwiftUICore/BannerMessage/BannerMultiMessageExample.swift
Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheetStyle.fiori.swift

Workaround for forcing list refresh when second layer array modified in bannerMultiMessage.

fix: 🐛 [JIRA:0] BannerMultiMessage enhancement

---

Apps/Examples/Examples/FioriSwiftUICore/ObjectHeader/ObjectHeaderViewScenarios.swift
Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCell_Spec_Jan2018.swift
Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelineItemsExample.swift
Sources/FioriSwiftUICore/Components/TextOrIcon.swift
Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
Sources/FioriSwiftUICore/Views/IconStack/IconStack+View.swift
Sources/FioriSwiftUICore/Views/TextOrIconView.swift
Sources/FioriSwiftUICore/_FioriStyles/StatusStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/SubstatusStyle.fiori.swift

jira: HCPSDKFIORIUIKIT-1975
A status contains a text and an icon in ObjectItem:
A Substatus contains a text and an icon and the icon shows in .trailing position in ObjectHeader:
A Substatus contains a text and icon and the icon shows in .leading position in TimeLine:

feat: 🎸 [jira: 1975] status and substatus should support both icon and text

---

Apps/Examples/Examples.xcodeproj/project.pbxproj
Sources/FioriSwiftUICore/Attachment/AttachmentThumbnailStyle+Extensions.swift
Sources/FioriSwiftUICore/Attachment/CameraView.swift

1. Add conditional compiler flag to visionOS and iOS
2. Add MandatoryAttachmentExample.swift into project, which was missing earlier and causing build failure as well
3. For **'camera' is unavailable in visionOS** , need further code investigation and clean up to remove camera API in other places where it should be used.  (e.g. in the menu to choose attachment)

fix: 🐛 build failed on visionOS

---

Apps/Examples/Examples.xcodeproj/project.pbxproj

project build fail: Build input file cannot be found: '/Users/***/***/Fiori/SwiftUI_SDK/cloud-sdk-ios-fiori/Apps/Examples/MandatoryAttachmentExample.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

fix: 🐛 MandatoryAttachmentExample file path error

---

Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
Sources/FioriSwiftUICore/Views/IconStack/IconStack+View.swift
Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheetStyle.fiori.swift
Sources/FioriSwiftUICore/_generated/StyleableComponents/ToastMessage/ToastMessage.generated.swift

1.Enum case 'tertiaryFill' cannot be used in a default argument value because 'FioriThemeManager' was not imported by this file; this is an error in the Swift 6 language mode
2.Immutable value 'icon' was never used; consider replacing with '_' or removing it
3.Variable 'element' was never mutated; consider changing to 'let' constant

chore: 🤖 clean up warnings

---

Sources/FioriSwiftUICore/Views/Carousel.swift

BREAKING CHANGE: 🧨 Carousel doesn't clip itself by default.
Before:
After:

fix: 🐛 remove clipped() in Carousel [jira: IOSSDKBUG-701]

---

Apps/Examples/Examples/FioriSwiftUICore/Picker/SegmentedControlExample.swift

After using the "Custom Style" test case in SegmentedControlExample, the customized style will be applied to other test cases as well. See screenshot for Checkout Indicator. Fix this by resetting UISegmentedControl appearance when SegmentedControlExample view disappears.
Before Fix:
After Fix:

test: 💍 restore default UISegmentedControl appearance

---

Apps/Examples/Examples/FioriSwiftUICore/ToastMessage/ToastMessageExample.swift
Sources/FioriSwiftUICore/_FioriStyles/ToastMessageStyle.fiori.swift

This PR prevents truncation of the title when the parent view has a small height and sets the font size to subhead/15pt.
Before             |  After
:-------------------------:|:-------------------------:

fix: 🐛 [HCPSDKFIORIUIKIT-2931] Fix Toast Message text styling

---

Sources/FioriSwiftUICore/Views/Carousel.swift

fix: 🐛 Carousel Empty Space Shown After Removing Last (jira:752

---

Sources/FioriSwiftUICore/_FioriStyles/ObjectItemStyle.fiori.swift

Title foreground color should be primary label, no need extra setting.
https://github.com/SAP/cloud-sdk-ios-fiori/issues/1103

fix: 🐛 object item title style to primary label

---

Sources/FioriSwiftUICore/_FioriStyles/ObjectItemStyle.fiori.swift

3 vertical spacing for title, subtitle..., which is right in code.
Just extra top spacing needed for description.
I can't find a latest spec for specific spacing between each elements. I'm not sure if this one is out of date.
|spec|app view|
|-|-|
|<img width="618" alt="Screenshot 2025-06-17 at 15 57 37" src="https://github.com/user-attachments/assets/20c262f0-dbc6-4a28-a589-d5f83ee3b14a" />|![Simulator Screenshot - iPhone 16 Pro Max - 2025-06-17 at 16 15 12](https://github.com/user-attachments/assets/34287589-350e-4e8e-8106-927fcec5d19b)|

fix: 🐛 extra top spacing for description in object item

---

Sources/FioriSwiftUICore/DurationPicker/DurationPickerViewWrapper.swift
Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItemSubview.swift
Sources/FioriSwiftUICore/Views/SortFilter/SortFilterCFGItemContainer.swift
Sources/FioriSwiftUICore/_FioriStyles/DurationPickerStyle.fiori.swift

Fix background color in dark theme.
Fix hour and minute label alignment in vertical.

fix: 🐛 [IOSSDKBUG-766]DurationPicker background in dark theme

---

Apps/Examples/Examples/FioriSwiftUICore/Picker/OrderPickerExample.swift
Sources/FioriSwiftUICore/_FioriStyles/OrderPickerStyle.fiori.swift
Tests/FioriSwiftUITests/FioriSwiftUICore/OrderPickerTests.swift

1. Set the default background of the list row to be transparent
2. Add a property to the OrderPickerItemModel to allow setting a custom background color for the list row.

fix: 🐛 [IOSSDKBUG-774] List row background in OrderPicker

---

Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

Build error:
cloud-sdk-ios-fiori/Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings:1:1: error: validation failed: Couldn't parse property list because the input data was in an invalid format (in target 'FioriSwiftUICore' from project 'FioriSwiftUI')

fix: 🐛 localization string format fix

---

Sources/FioriSwiftUICore/_localization/en.lproj/FioriSwiftUICore.strings

The "Cancel" string is duplicated in the localization file.

chore: 🤖 fix dupliate localization string(Cancel)

---

Apps/Examples/Examples/FioriSwiftUICore/FormCells/StepperViewExample.swift
Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift

Issue: https://github.com/SAP/cloud-sdk-ios-fiori/issues/1135

fix: 🐛 remove extra padding in stepper and apply it in example

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Sources/FioriSwiftUICore/_FioriStyles/CardMainHeaderStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift

This happens when cards are put into a List.

fix: 🐛 Card layout return small height some times

---

Sources/FioriSwiftUICore/Views/SortFilter/SortFilterCFGItemContainer.swift

fix: [IOSSDKBUG-822] Voiceover for SortFilterItem.switch not clear, value vocalised as "Not selected" or "Selected" instead of 0 or 1 

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Sources/FioriSwiftUICore/_FioriStyles/CardFooterStyle.fiori.swift

Footer compact mode:
Footer regular mode:

fix: 🐛 button layout issue in CardFooter [jira: IOSSDKBUG-892]

---

Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Sources/FioriSwiftUICore/_FioriStyles/CardFooterStyle.fiori.swift

App can overwrite the default card footer button width mode:

feat: 🎸 add card footer button width mode [jira: 0]

---

Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectItemListView.swift
Apps/Examples/Examples/FioriSwiftUICore/Onboarding/WelcomScreen/OnBoardingWelcomeScreenExamples.swift
Sources/FioriSwiftUICore/AIWritingAssistant/InternalWAForm.swift
Sources/FioriSwiftUICore/Components/CancellableResettableForm.swift
Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
Sources/FioriSwiftUICore/_FioriStyles/AIUserFeedbackStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/BackActionStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/EULAViewStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/UserConsentFormStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/WritingAssistantFormStyle.fiori.swift

Update to fixed size for buttons in navigation bar.
|feedback|sort & filter|W.A.|
|-|-|-|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-22 at 16 25 45" src="https://github.com/user-attachments/assets/ac1e40c0-56cc-45a8-966a-a0e2c99da1f2" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-22 at 16 25 45" src="https://github.com/user-attachments/assets/9635b5bb-16a1-4484-b6d6-fe142f26511c" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-22 at 16 26 17" src="https://github.com/user-attachments/assets/c3fa2008-6d84-432a-8047-ad89cd311202" />|
|Welcome|EULA|User Consent|
|-|-|-|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-08-22 …

feat: 🎸 [HCPSDKFIORIUIKIT-2999] tool bar buttons update

---

Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift

IOSSDKBUG-916 [SwiftUI] SegmentedControlPicker does not respond consistently when bannerMessageView modifier is applied

fix: 🐛 IOSSDKBUG-916 [SwiftUI] SegmentedControlPicker doesn't respond

---

.github/workflows/ci.yml
.github/workflows/pr_only.yml
Apps/Examples/Examples/FioriSwiftUICore/Card/MobileCardExample.swift
Makefile
Sources/FioriSwiftUICore/Views/Carousel.swift
Sources/FioriSwiftUICore/_FioriStyles/CardStyle.fiori.swift

New features:
1. add a new Carousel init with itemWidth
2. allow apps to set the initial visible item in the Carousel
Changes:
1. Update ci.yml and pr_only.yml to use macos-15 and Xcode 16.4
Once the a11y focus is changed the Carousel moves to the focused item automatically:
https://github.com/user-attachments/assets/5949dc39-4947-414d-838c-54b1d8832a0c
Snapping:
https://github.com/user-attachments/assets/9e1b554e-7fa1-4089-b61c-b30db23eee8e

fix: 🐛 [jira: IOSSDKBUG-865] Carousel moves to the A11Y focused

---

Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift

Ref: #1245 
Add a new api to allow show SPI vertical content programatically.
Currently, SAPFiori will reuse this component and pass a FUIButton as action.
And simultaneous tap gesture will not respond.
So we need handle the button's action by UIKit and update the `isPresented` binding value programmatically.
Can check the SPI in SAPFiori Test Cases -> Step Progress Indicator -> With Header and Sub-steps
And **All Steps** action does not work now.

fix: 🐛 new api allow show SPI vertical content programatically

---

Apps/Examples/Examples/FioriSwiftUICore/SideBar/EditableSideBarExample.swift
Sources/FioriSwiftUICore/_FioriStyles/SideBarListItemStyle.fiori.swift
Sources/FioriSwiftUICore/_FioriStyles/SideBarStyle.fiori.swift

[HCPSDKFIORIUIKIT-3047](https://jira.tools.sap/browse/HCPSDKFIORIUIKIT-3047) iOS 26 Liquid Glass issue of SideBar
This PR handle the below Sidebar related issues on iOS26:
1. The 'editMode' Environment variable can't work on iOS26 for UIkit Sidebar which wrapper the SWiftUI Sidebar.
2. The sidebar's width cannot properly fit the primary column for UINavigationSplitController or NavigationSplitView.
To resolve above two issues on iOS26, the 'editMode' Environment for UIkit Sidebar will not be used anymore to fix the first issue. Also, to let the sidebar's width fit the primary column's width automatically and don't use the original fixed width. At the same time, to expose some environment variables to let consumer have chance to customize the fixed width of Sidebar when they want to.

fix: 🐛 [HCPSDKFIORIUIKIT-3047] Fix Sidebar width in portrait mode and improve EditMode handling for iOS26
